### ISSUE TITLE
fastmerge, prfixmaster: Make git silent

### ISSUE THREAD

**Issue by adityadalal924** [vitorgalvao/tiny-scripts#10]
Similar to changes in https://github.com/vitorgalvao/tiny-scripts/commit/24aa96420cecdd5192a04d5c751a714cfb13fc32 (for `cask-repair`)

**Comment by vitorgalvao** [comment]
In `cask-repair` git messages are unnecessary (unless there’s an error, in which case they’ll show). Those other scripts, however, are all about git, so messages are important. It’s relevant to know which operations are being carried out, with which level of success, and what exactly those are doing.

With that in mind, at least for now I don’t intend to make them silent, as I find them useful.

**Comment by adityadalal924** [comment]
Got it, seems reasonable.

**Comment by vitorgalvao** [comment]
After some tests, I’ve decided to make git operations in `fastmerge` mostly silent. It’s more useful if you’re fastmerging a bunch of commits at once. Changes are already up.
