### ISSUE TITLE
how about use $HOMEBREW_EDITOR instead of $EDITOR in cask-repair

### ISSUE THREAD

**Issue by specter119** [vitorgalvao/tiny-scripts#105]
homebrew have already set `$HOMEBREW_EDITOR` as default editor to edit formula.
how about use it as default editor for `cask-repair`?

**Comment by vitorgalvao** [comment]
https://github.com/vitorgalvao/tiny-scripts/commit/7f504e807466cb15712b07e341d641a81c3d9d68

**Comment by specter119** [comment]
thanks
