### ISSUE TITLE
cask-repair suggest broken link because git is using ssh

### ISSUE THREAD

**Issue by sanyer** [vitorgalvao/tiny-scripts#107]
cask-repair returns this:

    You can upgrade the cask right now from your personal branch:
      brew cask reinstall https://raw.githubusercontent.com/sanyer/homebrew-cask.git/cask_repair_update-flume/Casks/flume.rb

Here, *homebrew-cask.git* is wrong as `current_tap` function doesn't remove .git if repo is cloned with SSH.
Function's command could be replaced with this one:

    basename (git remote get-url origin) .git

which is simple, self-explanatory and works for both HTTPS and SSH.

**Comment by vitorgalvao** [comment]
https://github.com/vitorgalvao/tiny-scripts/commit/26909c688b599de27f5b20bfef4b9f6c2419917b

Thank you.

**Comment by sanyer** [comment]
Nice.

Is there any particular reason you use sed instead of basename's `[suffix]` argument?

There is also similar code on line [118](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair#L118)
So, maybe it would be better to create function for `git remote get-url origin` and use it as is in function `require_correct_origin` and with basename in `current_tap`?

**Comment by vitorgalvao** [comment]
https://github.com/vitorgalvao/tiny-scripts/commit/a87e4ed18738fef211212a6aafb2d3564de075c2

**Comment by sanyer** [comment]
👍
