### ISSUE TITLE
cask-repair launches TextEdit three times, before continuing

### ISSUE THREAD

**Issue by gtmgianni** [vitorgalvao/tiny-scripts#109]
`cask-repair` opens cask files for me in TextEdit when they need to be modified. It says to quit the application so that the script can continue, but recently TextEdit has relaunched twice more after I tried to quit it. When I press Cmd-Q for the third time, TextEdit does not launch again, and the `cask-repair` script continues.

I don't have the `$EDITOR` or `$VISUAL` options set in my `.bash_profile` config file.

**Comment by vitorgalvao** [comment]
[Fixed](https://github.com/vitorgalvao/tiny-scripts/commit/ddc9e80a6d90c8d809046749a98630906af3de25).
