### ISSUE TITLE
cask-repair broken for GitHub users with 2FA enabled

### ISSUE THREAD

**Issue by sometoby** [vitorgalvao/tiny-scripts#115]
> If you’re opening an issue to report `Error creating pull request: Unprocessable Entity (HTTP 422)` in `cask-repair`

I had this same error and strongly suspect 2FA to be at fault. Disabling it on my account fixed the problem and cask-repair ran as expected afterwards.

**Comment by vitorgalvao** [comment]
2FA is not at fault, and this has been discussed before in the multiple issues regarding this. I use 2FA, as do many others, and we don’t have an issue.

**Comment by sometoby** [comment]
So enabling 2FA does not reproduce the issue reliably?

**Comment by vitorgalvao** [comment]
> So enabling 2FA does not reproduce the issue reliably?

It doesn’t reproduce the issue *at all* for myself and many others.
