### ISSUE TITLE
Error creating pull request: Unprocessable Entity (HTTP 422) (sorry)

### ISSUE THREAD

**Issue by fepegar** [vitorgalvao/tiny-scripts#117]
My command:
```
cask-repair --cask-version 4.8.1.26813,738961 slicer
```

I also tried [`brew untap caskroom/versions`](https://github.com/vitorgalvao/tiny-scripts/issues/95#issuecomment-321678847), but it didn't work after either.

I checked my GitHub connection, everything seems ok. Also, this is my ssh config file:
```
Host *
   AddKeysToAgent yes
   UseKeychain yes
   IdentityFile ~/.ssh/id_rsa

Host github.com
Hostname github.com
User git
IdentityFile ~/.ssh/id_rsa
```

**Comment by vitorgalvao** [comment]
I only look at this issue if I have clues on how to fix it. Otherwise there’s no point.

**Comment by fepegar** [comment]
Can I help you finding clues?

**Comment by vitorgalvao** [comment]
@fepegar If you search for the error on this repo, you’ll find multiple issues on the error and what has already been tried.
