### ISSUE TITLE
cask-repair: check if app name in app stanza is changed

### ISSUE THREAD

**Issue by muescha** [vitorgalvao/tiny-scripts#119]
https://github.com/caskroom/homebrew-cask/pull/42776

i run cask repair and the download url is changed.
the cask is submitted but it fails to install because the app name in app stanza also need to change.

is there an `app stanza app name check` possible or is it to much overhead?

**Comment by vitorgalvao** [comment]
> is it to much overhead?

It’s too much for something that happens rarely. `cask-repair` is meant to accelerate simple fixes, not be a comprehensive solution.
