### ISSUE TITLE
Check if PR with same name exists

### ISSUE THREAD

**Issue by Ty3uK** [vitorgalvao/tiny-scripts#120]
Hello. What about add checking of exist pull request before pushing commits? This will solve the problem of duplication pull requests with same package version. Here is some fast-written code for checking:
```bash
curl -s "https://api.github.com/repos/caskroom/homebrew-cask/pulls?state=open" | python -c "import sys, json; data = json.load(sys.stdin); has_pr = len(filter(lambda x: x['title'] == \"Update ${cask_name} to ${cask_version}\", data)) > 0; print(int(has_pr))"
```
Code return 1 if pull request with same name exists and 0 if not.

**Comment by vitorgalvao** [comment]
Checking the PR name is an insufficient metric. `cask-repair` lets you edit the cask to your will, so it’s entirely possible (and happens with some regularity) that two PRs with the same name have different changes. And in those cases the second one is generally the correct one, so prevent it from being submitted is detrimental.

**Comment by Ty3uK** [comment]
Ok, thanks for your answer. Cheers!
