### ISSUE TITLE
Cannot submit new PR using cask-repair with no error

### ISSUE THREAD

**Issue by OranShuster** [vitorgalvao/tiny-scripts#122]
Trying to update the cask "astro" using cask-repair but it refuses to submit it without any error message
I have used cask-repair many times before and it always works
I uploaded a video so you can better understand what is going on

https://streamable.com/pv47f

**Comment by vitorgalvao** [comment]
https://github.com/vitorgalvao/tiny-scripts/issues/116#issuecomment-353776486
