### ISSUE TITLE
move/rename from caskroom to homebrew breaks cask-repair

### ISSUE THREAD

**Issue by brianmorton** [vitorgalvao/tiny-scripts#126]
```
$ cask-repair -b -v 57.0.0 kullo
`caskroom/cask` not tapped. Tapping…
`caskroom/versions` not tapped. Tapping…
`caskroom/fonts` not tapped. Tapping…
`caskroom/eid` not tapped. Tapping…
`caskroom/drivers` not tapped. Tapping…
Updating taps… Already up-to-date.
No such cask was found in any official repo (kullo).

$ brew cask search kullo
==> Exact Match
kullo
```

I hacked a local copy by replacing some of the refs (so I can still submit PRs with the tool, although it throws some errors and I don't think it updates correctly), but am not confident enough in the fix to submit a PR.

**Comment by vitorgalvao** [comment]
Crap, I was hoping maybe the automatic redirect would make this not immediately necessary.

> but am not confident enough in the fix to submit a PR.

Please do. I’m really tired right now and will likely go to sleep soon, so I won’t be able to fix it for a few hours. Having it semi-working now will be better than waking up to numerous bug reports.

**Comment by brianmorton** [comment]
Alright, it's a two line change but I'll submit one if you want. Again, I don't think this really solves the problem but it did allow me to still use `cask-repair` to submit PRs.

**Comment by brianmorton** [comment]
@vitorgalvao PR submitted

**Comment by vitorgalvao** [comment]
Thank you. Made a few more quick updates and hope I got most of it working.

**Comment by fepegar** [comment]
As a reference for next users having this problem, I ran `brew upgrade cask-repair` to make avoid the error.
