### ISSUE TITLE
`climergebutton`: suggestion: save token in config

### ISSUE THREAD

**Issue by OliverJAsh** [vitorgalvao/tiny-scripts#131]
Thanks for building `climergebutton`!

I'd like to suggest a way to save the token to some config file, so it doesn't have to be specified with each command.

Do you know if any existing patterns/tools to help us do this? How does `hub` do it?

**Comment by vitorgalvao** [comment]
`hub` saves it in plaintext under `~/.config/hub`. That’s not a method I like very much; I’d rather save it to the Keychain. Though that makes it macOS-only, the current method would still work for non-macOS.

Storing it and reading it isn’t the problem, but making it a good experience. I know how to do it, but I don‘t know if it’s worth the time to do, as I don’t know how many people use this script.

For now, if you add to your shell startup file something like  `alias climergebutton='climergebutton --token "whatever_your_token_is"`, it’ll work the same as if it used a config file.

**Comment by OliverJAsh** [comment]
Thanks!
