### ISSUE TITLE
cask-repair -b -v $VERSION $TOKEN is still interactive

### ISSUE THREAD

**Issue by brianmorton** [vitorgalvao/tiny-scripts#134]
specifically discovered with the following cask:
ondesoft-itunes-converter

It seems that casks which don't use string interpolation in the url (eg. no `#{version}` or similar) will prompt for a new URL even if the -b flag is passed.

```
Paste the new URL (or leave blank to use the current one)
>
```

edit: fixed a positive to a negative ;)

**Comment by vitorgalvao** [comment]
> specifically discovered with the following cask:
> ondesoft-itunes-converter

[That cask doesn’t use string interpolation in the URL](https://github.com/Homebrew/homebrew-cask/blob/bb1f48864c3505ccb16cf6ffa03b93ed1c331aa3/Casks/ondesoft-itunes-converter.rb#L5).

**Comment by brianmorton** [comment]
Yes, I mis-typed. Casks w/o string interpolation force that prompt it seems.

**Comment by vitorgalvao** [comment]
That’s by design. Presumably if the version changed, the URL also changed. `cask-repair` works fine in scripts but was primarily designed for manual updates. If you *know* the URL is to be kept the same, give it as an argument and take advantage of `_stanza`:

```bash
cask-repair --blind-submit --cask-version "${version}" --cask-url "$(brew cask _stanza url "${token}")" "${token}"
```

**Comment by brianmorton** [comment]
I agree with the sentiment, but in practice we have many casks with a fixed url even when we update the version so this did not operate as I expected it would (by breaking the blind-submit).

Thank you for providing a workaround with `-u` / `--cask-url`.

**Comment by brianmorton** [comment]
FWIW, I also generally try to avoid calling `brew` in my scripting as the overhead involved is usually much slower than parsing it from the cask myself.

Calling `brew <anything` will take at least a couple of seconds, whereas parsing the `cask.rb` is a fraction of a second, so I only do it when I can't easily repeat the functionality (such as with appcast urls, which sometimes use string interpolation for things like `#{version.major}`).

When I have to operate automatically on ~2000-4000 casks, a couple of `brew` calls can easily 2x-5x the scripts runtime.
