### ISSUE TITLE
Error: Cask 'slicer-nightly' is unavailable: Failed to download

### ISSUE THREAD

**Issue by fepegar** [vitorgalvao/tiny-scripts#136]
Hello,

I had [this problem](https://github.com/vitorgalvao/tiny-scripts/issues/126) and fixed it [like this](https://github.com/vitorgalvao/tiny-scripts/issues/126#issuecomment-401044865). After that I tried to "upgrade the cask right now from your personal branch" and got an error:

```shell
brew cask reinstall https://raw.githubusercontent.com/fepegar/homebrew-cask-versions/cask_repair_update-slicer-nightly/Casks/slicer-nightly.rb
==> Downloading https://raw.githubusercontent.com/fepegar/homebrew-cask-versions/cask_repair_update-slicer-nightly/Casks/slicer-nightly.rb.

curl: (22) The requested URL returned error: 404 Not Found
Error: Cask 'slicer-nightly' is unavailable: Failed to download https://raw.githubusercontent.com/fepegar/homebrew-cask-versions/cask_repair_update-slicer-nightly/Casks/slicer-nightly.rb. Did you mean “slicer-nightly ✔”?
```

Note the `Did you mean “slicer-nightly ✔”?`.

**Comment by vitorgalvao** [comment]
That’s because your repo’s name is still the old one (`homebrew-versions` instead of `homebrew-cask-versions`). Fix that and it’ll work.
