### ISSUE TITLE
cask-repair custom comments

### ISSUE THREAD

**Issue by brianmorton** [vitorgalvao/tiny-scripts#138]
In a similar vein to the `-c` flag, would you be interested in another flag that let me add a custom string to the PR? I frequently have something to add to my PR that I would rather just do when running `cask-repair` instead of pulling up the PR and editing it or adding a comment.

I would be happy to do the fork/pr if you agree.

**Comment by vitorgalvao** [comment]
Yes, I’ll take a PR for it.

Make the flag `-m <message>, --comment-issue <message>`. If you notice that it interacting with `-c <number>, --closes-issue <number>` makes the code a bit convoluted, scrape it and have `-c` become `--comment-issue`. We don’t see a lot of `--closes-issue` in submissions anyway, and even if people use the current `-c` in scripts, it wouldn’t be a breaking change.
