### ISSUE TITLE
Use $EDITOR to edit cask?

### ISSUE THREAD

**Issue by tsparber** [vitorgalvao/tiny-scripts#14]
What do you think about using `$EDITOR` to edit the cask file?
Or any other way to override  [`open -W`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair#L263)?

`EDITOR="open -W" cask-repair` could still be used to get the same behavior.

**Comment by vitorgalvao** [comment]
Why, though? A cask will always be a `.rb` file, so opening with whatever app you have as the default to open ruby files seems appropriate.

Really need a use case, here.

**Comment by tsparber** [comment]
I open `.rb` files by default with a gui app which is also used for other tasks and needs to be completely closed to allow `cask-repair` to continue.
My use case would be to open a cmdline editor, instead of a (slow starting) GUI.
I would be perfectly fine, if this could be achieved by a cmdline argument :smiley:

**Comment by vitorgalvao** [comment]
Your point is perfectly reasonable.

However, there’s a problem (which is why `-W` is needed). Say your `$EDITOR` is `atom`, or some other command that calls a GUI app. It will spawn that GUI and then exit from the shell, meaning `cask-repair` will start the next loop without the cask having actually been changed.

How do we account for that?

**Comment by tsparber** [comment]
`atom` has a `-w/--wait` option, sublime text [too](https://www.sublimetext.com/docs/2/osx_command_line.html). I think a sensible `$EDITOR` choice should wait until exited (or if supported include the `-w` flag to wait until the new windows is closed). `git` uses `$EDITOR` (by default). If `$EDITOR` exits immediatly you would also have a problem there.

**Comment by vitorgalvao** [comment]
Though that assumes the user has made a sensible `$EDITOR` choice, which perhaps isn’t a great bet, I do agree that if you are setting `$EDITOR`, you should do it correctly (and it isn’t hard), so [there it is](https://github.com/vitorgalvao/tiny-scripts/commit/54be1bcf868ea3e0fd1c85222ac23a954e416159).

**Comment by tsparber** [comment]
Thanks :+1:
