### ISSUE TITLE
Completions for the scripts

### ISSUE THREAD

**Issue by MindTooth** [vitorgalvao/tiny-scripts#143]
Hi,

Wanted to create a completion for `cask-repair` in `fish`.  But there does not seems to be a place to add those.

Thoughts on the matter?  I could upstream, but seeing how slow they release new versions, I rather not.

**Comment by vitorgalvao** [comment]
Maybe a `cask-repair-completions` repo?

**Comment by MindTooth** [comment]
Well, not that I use your other ones, but maybe make it more generic.  Or just a completion folder inside this repo.

**Comment by vitorgalvao** [comment]
> but maybe make it more generic

I think `cask-repair` is by far the most popular. Making a repo specific to its completions might inspire others to do the bash and zsh versions. I’ve also been toying with the idea of splitting this repo into more specific `tiny`repos (for example, I have four pinboard scripts, they could have their own repo).

Do you prefer to make the repo yourself, or that I make it and give you write access? I’m unlikely to ever touch it so you’d have to write the instructions as well (I might edit those for consistency).

**Comment by MindTooth** [comment]
You go ahead.  Feel it's better you have ultimate power.  I'll gladly take write perm. for the moment to get it started.

**Comment by vitorgalvao** [comment]
Repo created and invite sent. Feel free to merge your submissions at will, but I ask that you submit changes/additions as PRs instead of directly pushing.
