### ISSUE TITLE
New Mac, Mojave, cask-repair issue

### ISSUE THREAD

**Issue by Jestre** [vitorgalvao/tiny-scripts#148]
Received a new MacBook, installed Homebrew and trying to submit a cask-repair job for an app.  Everything works until the actual submission step, where it repeatedly asks to submit, and indicates that it is trying to install rubocop

    • ==> Installing or updating 'rubocop-cask' gem
    Building native extensions.  This could take a while...

At first I thought this could be due to the fact that I did not yet have the Homebrew version of Ruby installed, but after installing that, nothing changed.

I found several other closed issues which reference a similar problem, all of which seemed to imply that removing prior rubocop installations would resolve it, but I had none installed:

    sudo gem uninstall -ax rubocop rubocop-cask
    Password:
    Gem 'rubocop' is not installed
    Gem 'rubocop-cask' is not installed

Running the follow-on command yields the following:

```
$ brew cask style
==> Installing or updating 'rubocop-cask' gem
Building native extensions.  This could take a while...
ERROR:  Error installing rubocop-cask:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181001-41654-xlsc8u.rb extconf.rb
creating Makefile

current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
make "DESTDIR=" clean

current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.1/ext/jaro_winkler
make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `adj_matrix.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.1 for inspection.
Results logged to /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1/gem_make.out
Error: Failed to install/update the 'rubocop-cask' gem.
```

Path:

    /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/go/libexec/bin:/Users/Jestre/Devel/golang/bin:/Users/Jestre/Devel/bin

This all does work fine on my old Mac, and the only difference I see in `brew config` is that on the old Mac, HOMEBREW_RUBY points to the Homebrew Ruby whereas on the new Mac, it points to system Ruby.

Any ideas?

**Comment by vitorgalvao** [comment]
This is a problem with installing the gem from `brew cask style`, not an issue with `cask-repair`. Please open a bug report about `brew cask style` on the Homebrew repo.
