### ISSUE TITLE
cask-repair: more specific branch names

### ISSUE THREAD

**Issue by jawshooah** [vitorgalvao/tiny-scripts#15]
The `update-{{cask}}` naming convention for branches created by `cask-repair` seems a bit too broad, especially since `--delete-branches` deletes any branches matching that convention. It's very possible that this step would clobber branches completely unrelated to `cask-repair`. I'd suggest as an alternative: `cask-repair/update-{{cask}}`.

**Comment by vitorgalvao** [comment]
Perfectly reasonable. Will do.

**Comment by vitorgalvao** [comment]
[Done](https://github.com/vitorgalvao/tiny-scripts/commit/f0018e3775e381d2cc6c67b749a9bbe6651e7b3f).

**Comment by jawshooah** [comment]
:+1:
