### ISSUE TITLE
Github errors while pushing - git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by ralphrmartin** [vitorgalvao/tiny-scripts#152]
I have just tried cask-repair for the first time, for
cask-repair wch-ch34x-usb-serial-driver

Everything seemed to go OK except for the last step which reports 
git@github.com: Permission denied (publickey).

I performed
hub issue
as instructed, and all seemed to go OK - it asked for my username and password, and no error was reported.

It then said
```
A `ralphrmartin` remote does not exist. Creating it now…
Updating ralphrmartin
From https://github.com/Homebrew/homebrew-cask-drivers
 * [new branch]      master     -> ralphrmartin/master
new remote: ralphrmartin
```
and all seemed to go OK until try to do the pull request:

```
 cask 'wch-ch34x-usb-serial-driver' do
-  version '1.4'
-  sha256 'b190f612b833727b2006f362a835f7e97177b580e45cef253e164202106c48eb'
+  version '1.5'
+  sha256 'e2a1dcf60c5ce54abcc8cb7ccc202f258902b7ed73488a43916afb7c01a2a25a'
 
   url 'http://www.wch.cn/downloads/file/178.html'
   name 'WCH USB serial driver for CH340/CH341'
------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
There were errors while pushing:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please fix the errors and try again. If the issue persists, open a bug report on the repo for this script (https://github.com/vitorgalvao/tiny-scripts).
```
The only thing I can think of is that this cask lives in 
Homebrew/homebrew-cask-drivers
but cask-repair does not seem to have a way of specifying that.

**Comment by ralphrmartin** [comment]
OK, I now just got an email from github which says

`A personal access token (hub for ralph@ralph.local) with repo scope was recently added to your account. Visit https://github.com/settings/tokens for more information.
`
which does not look very helpful. I suspect that local internet name is what is breaking something.

**Comment by vitorgalvao** [comment]
> but cask-repair does not seem to have a way of specifying that.

It’s automatic.

This is not a `cask-repair` issue, but rather is concerned with your configuration or `hub`. If you search this repo, you’ll [find similar issues](https://github.com/vitorgalvao/tiny-scripts/search?q=Could+not+read+from+remote+repository&type=Issues). Frankly, I don’t have the time or the willpower to continue debugging these problems when the issues are in the user’s configuration or the dependencies. I can deal with the latter (I’m considering dumping `hub` and using the API myself), but as for the former, continued free technical support for something that is not my fault can eventually burn me out, so I’ll pass.

**Comment by ralphrmartin** [comment]
What was missing from your instructions is that one needs to add an SSH key to ones github account, as explained below.

https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

I am posting this here in case it helps someone else. It would be useful to also add it to your instructions on how to use cask-repair..

**Comment by vitorgalvao** [comment]
> It would be useful to also add it to your instructions on how to use cask-repair

But they are not instructions on how to use `cask-repair`; they are instructions on how to use git. I use Github via HTTPS, which they recommend, not via SSH key. I can’t (shouldn’t) be expected to provide instructions on how to work with every single configuration method. I’ve been doing this long enough to know there’s always *someone* that wants *something* a bit behind their experience level. If I acceded to every one of those requests, I’d have instructions on how to invoke commands from a Terminal (not an exaggeration). I have to draw the line somewhere.

**Comment by ralphrmartin** [comment]
I wasn't using Github via SSH key by before I installed cask-repair, but cask-repair would not work without setting one up. I've no idea how it came about that cask-repair was trying to use a public key to access github. Anyway, maybe my suggestion here will help anyone else who ends up with the same error message.  Thanks.

**Comment by selrond** [comment]
@ralphrmartin thank you! 
@vitorgalvao the reqirement of having ssh set up definitely needs to be mentioned somewhere. Are you open to PRs?

**Comment by vitorgalvao** [comment]
> the reqirement of having ssh set up definitely needs to be mentioned somewhere.

There is no such requirement. I don’t use it, and `cask-repair` works just fine.

**Comment by selrond** [comment]
@vitorgalvao that's really odd then...

**Comment by jabenninghoff** [comment]
I had the same problem as described here, but it was caused because I had a separate ssh identity file for GitHub. I fixed the issue by adding a host configuration for github.com with the correct `IdentityFile` to `~/.ssh/config`
