### ISSUE TITLE
Error message "Only one cask-repair instance can be run at once." after clean install

### ISSUE THREAD

**Issue by PierreMesure** [vitorgalvao/tiny-scripts#157]
Hey,

I just installed cask-repair and I always get the same message: 

> Only one cask-repair instance can be run at once.

It seems this error message was added [in this commit](https://github.com/vitorgalvao/tiny-scripts/commit/72956e34b6581f013c86b5c329843e0f2ffddd74) so I'm wondering if it isn't a bug that was added recently.

**Comment by vitorgalvao** [comment]
Delete this file: `/tmp/cask-repair.lock`.
