### ISSUE TITLE
`cask-repair`: Do not redownload file if identical version

### ISSUE THREAD

**Issue by adidalal** [vitorgalvao/tiny-scripts#16]
Trying out the outdated appcast scripts, there's a bunch of Casks that have an updated appcast, but not a version bump, for one reason or another.

If the same version is given, `cask-repair` should only download/update the appcast checkpoint.

**Comment by vitorgalvao** [comment]
Unfortunately, such a check is unadvisable. See for example [a recent case](https://github.com/bit101/gifloopcoder/issues/17#issuecomment-181383253). Like that, I occasionally find others. An unchanging version insn’t synonymous with an unchanging `sha256`.

I’m not sure there’s a good solution for this, but I’d rather err on the side of actually making sure the cask is correct.

**Comment by adidalal** [comment]
Interesting, thanks for checking it out!
