### ISSUE TITLE
cd $(brew --repository) && hub issue doesn't not adequately guide the user through setup

### ISSUE THREAD

**Issue by Lucurus** [vitorgalvao/tiny-scripts#160]
Hi,

first, of all thank you very much for maintaining this script.

I tried repairing a cask using the script with the following steps:

1. `cd $(brew --repository) && hub issue`
2. `cask-repair [Name]`

Got the error `hub is not configured. To do it, run (cd $(brew --repository) && hub issue). Your Github password will be required, but is never stored.` So I ran:

1. `cd $(brew --repository) && hub issue`
2. Put in my details
3. `cask-repair [Name]`
4. And got the following error:

_git@github.com: Permission denied (publickey)._
_fatal: Could not read from remote repository._

_Please make sure you have the correct access rights_
_and the repository exists._

_Please fix the errors and try again. If the issue persists, open a bug report on the repo for this script_ _(https://github.com/vitorgalvao/tiny-scripts)._

It's fixable by adding the ssh key to GitHub, but since this script takes care of everything else otherwise, it might be good to add that step as well.

**Comment by Lucurus** [comment]
Sorry, should have said, that this is regarding [cask-repair](https://github.com/vitorgalvao/tiny-scripts#cask-repair)

**Comment by Lucurus** [comment]
Maybe one could direct the user simply to https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by vitorgalvao** [comment]
The error is git/hub related, so better messaging for that error belongs in those projects.
