### ISSUE TITLE
[Request] cask-repair: Check for missing URL comment when URL and homepage hostnames differ

### ISSUE THREAD

**Issue by 404NetworkError** [vitorgalvao/tiny-scripts#162]
Per the requirement [when URL and homepage hostnames differ](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment), I would appreciate if you could add functionality to check and make sure the comment exists when changing the url. I ran into this problem in Homebrew/homebrew-cask#59033 when `cask-repair` said everything was correct but the Travis checks informed me about my mistake.

Also, it would be nice if the URL changed back to matching the homepage hostname, the check should make sure the comment gets removed.

(P.S. Thank you for your efforts in making the Homebrew Cask upgrade process easier.)

**Comment by vitorgalvao** [comment]
> functionality to check and make sure the comment exists when changing the url

That is already present. It’s as part of `brew cask style` (that `cask-repair` runs). But I commented out that section when doing some tests before and committed that on accident. I’ve now fixed it, please `brew upgrade cask-repair`.

> Also, it would be nice if the URL changed back to matching the homepage hostname, the check should make sure the comment gets removed.

That is something for the [cop](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/cask/homepage_matches_url.rb) to do with the `--fix` flag (and `cask-repair` would get it for free). I don’t think it does it (my `style` is broken so I cannot check), so you should make the feature request in the repo, after confirming it doesn’t do it.

> Thank you for your efforts in making the Homebrew Cask upgrade process easier.

Thank you for the kind words.

**Comment by 404NetworkError** [comment]
> That is something for the [cop](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/cask/homepage_matches_url.rb) to do with the `--fix` flag (and `cask-repair` would get it for free). I don’t think it does it (my `style` is broken so I cannot check), so you should make the feature request in the repo, after confirming it doesn’t do it.

You are correct that the cop does not check when the URL changes back. I'll make the request now.
