### ISSUE TITLE
cask-repair infinite confirmation loop

### ISSUE THREAD

**Issue by faradaytrs** [vitorgalvao/tiny-scripts#168]
![Screenshot 2019-03-27 at 18 08 21](https://user-images.githubusercontent.com/3426470/55067802-595ec400-50bb-11e9-9ebb-efeffb1376da.png)
I try to submit casks but it keeps asking me to confirm again and again.

**Comment by vitorgalvao** [comment]
https://github.com/vitorgalvao/tiny-scripts/issues/150

The problem is with `brew cask style`. That’s what you need to fix.
