### ISSUE TITLE
cask-repair does not obey 'HOMEBREW_NO_AUTO_UPDATE' environment variable

### ISSUE THREAD

**Issue by core-code** [vitorgalvao/tiny-scripts#172]
it would be great if cask-repair would obey the 'HOMEBREW_NO_AUTO_UPDATE' environvent variable or if there would be another way to turn-off the 'brew update' running before each and every cask-repair - which seems to be the operation that takes the most time.

if you tell me the preferred way to implement this (obey the variable or add a new flag), i can probably come up with a patch ;)

**Comment by vitorgalvao** [comment]
[Done](https://github.com/vitorgalvao/tiny-scripts/commit/565adef470e195f5d3fb10aa1881de1422f2e734).

**Comment by core-code** [comment]
awesome, thanks;)
