### ISSUE TITLE
`Appcast` Audit Preventing Updates from ML

### ISSUE THREAD

**Issue by ran-dall** [vitorgalvao/tiny-scripts#176]
@vitorgalvao Hey man, the ML is having issues running cask-repair sometimes. I've been trying to be less dependant on it but at the moment it's still a dependency. Anyways, the warning on the audit for the `appcast` is preventing the ML from submitting a `cask` that has an `update` but the `appcast` hasn't been updated. When the ML confirms to submit, it just duplicates the same issue.

Some examples
![Screen Shot 2019-07-09 at 11 40 32 AM](https://user-images.githubusercontent.com/17261190/60914477-75d3d600-a23e-11e9-9521-6b7c848d107d.png)
![Screen Shot 2019-07-09 at 11 37 17 AM](https://user-images.githubusercontent.com/17261190/60914478-766c6c80-a23e-11e9-9a07-8124d7c2185f.png)
![Screen Shot 2019-07-09 at 11 40 54 AM](https://user-images.githubusercontent.com/17261190/60914476-75d3d600-a23e-11e9-9f7b-49da9a8a35e5.png)

**Comment by vitorgalvao** [comment]
Fixed.

**Comment by ran-dall** [comment]
@vitorgalvao 🙏 Much obliged, as always.
