### ISSUE TITLE
cask-repair: Repository not found when submitting

### ISSUE THREAD

**Issue by i0ntempest** [vitorgalvao/tiny-scripts#179]
Shell output:
```Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
Enter passphrase for key '/Users/[username]/.ssh/id_rsa': 
There were errors while pushing:
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I was able to use this script a while ago but since a few days ago it stopped working.

**Comment by vitorgalvao** [comment]
Unfortunately, you’ll need to [find the solution somewhere else](https://stackoverflow.com/questions/10116373/git-push-error-repository-not-found).

You’re using SSH access, which I don’t offer support for (I’ve already spent too much of my free time and sanity doing so), and this is not a widespread issue.
