### ISSUE TITLE
cask-repair incompatible with Linux

### ISSUE THREAD

**Issue by andyli** [vitorgalvao/tiny-scripts#182]
I'm trying to use cask-repair in Linux, with linuxbrew (my mac died, that's why). The command often ends with an error about `all_colors: readonly variable` as follows:

```
$ cask-repair --cask-version '32.0.0.293' --blind-submit flash-player-debugger
`homebrew/cask-drivers` not tapped. Tapping…
==> Tapping homebrew/cask-drivers
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers'...
remote: Enumerating objects: 169, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 169 (delta 3), reused 39 (delta 1), pack-reused 0
Receiving objects: 100% (169/169), 76.52 KiB | 1.16 MiB/s, done.
Resolving deltas: 100% (3/3), done.
Tapped 138 casks (186 files, 386.4KB).
Already up-to-date.
Updating taps… /home/linuxbrew/.linuxbrew/bin/cask-repair: line 24: all_colors: readonly variable
```

Maybe it's due to different versions of bash between ubuntu and mac? My bash version:
```
$ bash --version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

It would be nice if the script can work in Linux, if all needed is some minor changes.

**Comment by vitorgalvao** [comment]
> /home/linuxbrew/.linuxbrew/bin/cask-repair: line 24: all_colors: readonly variable

I understand what the message says, but it doesn’t clarify why that’s an issue. Yes, the variable is read only, and it should be. The script complies only with bash 3 because that’s the version included in macOS due to the highly restrictive GPL.

I don’t have a Linux machine on hand, so to fix this I’ll need your help. The simplest solution might be to change the shell to `zsh`. Change the top line to `#!/usr/bin/env zsh`. Does it work? What’s the output of `which zsh`?

**Comment by andyli** [comment]
Switching to zch gave different error:
```
$ cask-repair --help
/home/linuxbrew/.linuxbrew/bin/cask-repair:154: no matches found: has_interpolation?
```

My zsh version (installed with `brew install zsh`):
```
$ zsh --version
zsh 5.7.1 (x86_64-pc-linux-gnu)
```

**Comment by andyli** [comment]
Maybe it's this: https://stackoverflow.com/questions/45409822/bash-local-and-readonly-variable

I changed `readonly local all_colors` to `local -r all_colors` and it works now.

**Comment by vitorgalvao** [comment]
Thank you for that link. I’ve updated not only `cask-repairs` but my other scripts that were doing it wrong.
