### ISSUE TITLE
cask-repair -v 7.4.1,0 xampp fails

### ISSUE THREAD

**Issue by mmoehring** [vitorgalvao/tiny-scripts#186]
When trying to `cask-repair -v 7.4.1,0 xampp` I am getting the following error:

    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

Full log: [cask-repair.log](https://github.com/vitorgalvao/tiny-scripts/files/4093933/cask-repair.log)
SSH is using the correct key and connects successfully when checking via `ssh -v git@github.com`

**Comment by vitorgalvao** [comment]
That’s a `git` error, not a `cask-repair` error. Search for the message online.
