### ISSUE TITLE
cask-repair fails to find cask ip-scanner

### ISSUE THREAD

**Issue by ralphrmartin** [vitorgalvao/tiny-scripts#189]
cask-repair  is rather oddly reporting that a cask is not in any repo, when it seems to be:

```
ralph@ralph ~ $ brew cask info ip-scanner                                          
ip-scanner: 3.83
https://10base-t.com/macintosh-software/ip-scanner/
/usr/local/Caskroom/ip-scanner/3.83 (64B)
==> Name
IP Scanner
==> Artifacts
IP Scanner.app (App)
ralph@ralph ~ $ cask-repair ip-scanner           
Already up-to-date.
Updating taps… 
No such cask was found in any official repo (ip-scanner).
```
yet the cask is found when trying a reinstall
```
brew cask reinstall ip-scanner
==> Downloading https://10base-t.com/downloads/IPScanner_3.83.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'ip-scanner'.
```

**Comment by vitorgalvao** [comment]
```console
$ brew cask info ip-scanner
Error: Cask 'ip-scanner' is unavailable: No Cask with this name exists. Did you mean “angry-ip-scanner”?

$ brew search ip-scanner
==> Casks
angry-ip-scanner
```

`cask-repair` is correct. You must have gotten it from another repo or it was deleted/renamed in the official repos.

**Comment by ralphrmartin** [comment]
Ah, I see. Thank you. I think I it must have been renamed as I don't remember getting it from elsewhere. 

Clearly this is not cask-repair's fault - but maybe the cask system itself needs to consider reinstalling casks whose names change, to avoid confusion? Do you think this is worth raising as an issue there?

**Comment by ralphrmartin** [comment]
Please ignore the previous remark. 
ip-scanner is not the same as angry-ip-scanner.
Perhaps it was deleted.

**Comment by vitorgalvao** [comment]
> but maybe the cask system itself needs to consider reinstalling casks whose names change, to avoid confusion?

It should. [We want it but don’t yet have it](https://github.com/Homebrew/homebrew-cask/pull/76526#issuecomment-583179937). PRs welcome.
