### ISSUE TITLE
hub installed but cask-repair says it's not

### ISSUE THREAD

**Issue by brandonb927** [vitorgalvao/tiny-scripts#19]
When I try to run `cask-repair`, it tells me that I need to install `hub`, however I've had `hub` installed for over a year and use it daily. Let me know if you need any more info or if this is a known issue. I checked the closed issues and didn't find anything related to this.

```
❯ cask-repair --help

This script requires 'hub' installed and configured.
If you have [Homebrew](http://brew.sh), you can install it with 'brew install hub'.
To configure it, run 'cd /usr/local && hub issue'. Your Github password will be required, but is never stored.

❯ which hub
/usr/local/bin/hub

❯ cask --version
0.60.0 (git revision 52547; last commit 60 minutes ago)
```

OS X 10.11.4
cask v0.60

**Comment by vitorgalvao** [comment]
The problem is likely that it isn’t configured (in a why `cask-repair` expects).

Does `grep 'oauth_token:' "${HOME}/.config/hub" 2>/dev/null` output something?

**Comment by brandonb927** [comment]
It does not, but I didn't expect the `if hub exists OR oauth_token in hub config file ...` check to fail if `hub` exists AND the file has the correct `oauth_token` attribute. I'm not sure how to add this with `hub` either. Thoughts?

**Comment by vitorgalvao** [comment]
> I'm not sure how to add this with `hub` either.

It tells you in the message:

> To configure it, run 'cd /usr/local && hub issue'. Your Github password will be required, but is never stored.

**Comment by brandonb927** [comment]
I did run that, however it still didn't work after re-running `cask-repair` as the `~/.config/hub` doesn't exist

**Comment by vitorgalvao** [comment]
And did it ask for your password?

What’s the output of `brew info hub`?

**Comment by brandonb927** [comment]
It didn't ask for my password :\ If it's any consolation, I do have `GITHUB_TOKEN` set in my `~/.zshrc` so it might be using that?

Output of `brew info hub` is:
```
❯ brew info hub
hub: stable 2.2.3 (bottled), HEAD
Add GitHub support to git on the command-line
https://hub.github.com/
/usr/local/Cellar/hub/2.2.3 (9 files, 10.3M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/hub.rb
==> Dependencies
Build: go ✔
==> Options
--without-completions
	Disable bash/zsh completions
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
```

**Comment by vitorgalvao** [comment]
> I do have `GITHUB_TOKEN` set in my `~/.zshrc` so it might be using that?

`hub` does support that, but shouldn’t be using it since the script shouldn’t be able to get to that. Try removing it from your `.zshrc` and see if it still works.

**Comment by brandonb927** [comment]
I'll try the next time I use cask-repair. Thanks for the help, much appreciated!

**Comment by vitorgalvao** [comment]
Alright, thank you.

If we can figure it out, I’ll be able to add another check to `cask-repair` to not grab false positives like this.
