### ISSUE TITLE
cask-repair re-downloads same artifact url for different casks 

### ISSUE THREAD

**Issue by yurikoles** [vitorgalvao/tiny-scripts#191]
E.g. I seem to be the only maintainer of `telegram-desktop` and `telegram-desktop-dev`. 
As per common agreement we update non-stable cask to stable version if there is no more fresh unstable version. So when I update both formulas like:
```
cask-repair telegram-desktop -v 2.1.4 -b
cask-repair telegram-desktop-dev -v 2.1.4 -b -i
```
`cask-repair` always downloads same artifact for second cask, despite the fact that URLs are the same, file path too, e.g. 
```
66b90dccb54a8d0144d8a24f442fdc7a32347230ed6c289349380d830ff5469b--tsetup.2.1.4.dmg
```

**Comment by vitorgalvao** [comment]
That’s by design. It force fetches.
