### ISSUE TITLE
cask-repair broken with Git 2.21 (default in Mojave's Xcode command line tools)

### ISSUE THREAD

**Issue by jboekesteijn** [vitorgalvao/tiny-scripts#192]
The changes in commit bf595ff092b4efafffcfe1dfd63b51c221db7fe5 break `cask-repair` with Git version 2.21.1 included with the Xcode command line tools in 10.14.6:
```
error: unknown option `show-current'
```
This option was introduced in Git 2.22 so it is not available using the standard Xcode command line tools in Mojave. Are users expected to upgrade to Catalina and/or install a newer Git version?

**Comment by vitorgalvao** [comment]
Far from me from requiring someone to upgrade to Catalina. Please don’t.

I’ve reverted that change.
