### ISSUE TITLE
404 error opening cask-repair pull request

### ISSUE THREAD

**Issue by trolley** [vitorgalvao/tiny-scripts#200]
I'm trying to use `cask-repair` to submit a new version of an app and get the following error:

```
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/homebrew/homebrew-cask exists?

There was an error submitting the pull request. Please open a bug report on the repo for this script (https://github.com/vitorgalvao/tiny-scripts).
```

Connections to GitHub work fine:

```
❯ ssh -T git@github.com
Hi trolley! You've successfully authenticated, but GitHub does not provide shell access.
```

OS: macOS 11.0.1
git: 2.29.2

**Comment by vitorgalvao** [comment]
Like most problems in `cask-repair`, [this is on `hub`’s side](https://github.com/github/hub/issues/1346), so it’s out of my hands. I no longer debug `hub` issues (I’ve mentioned that in another PR).

It is was a simple version bump, I recommend you use `brew bump-cask-pr` instead.
