### ISSUE TITLE
brew cask is deprecated

### ISSUE THREAD

**Issue by ralphrmartin** [vitorgalvao/tiny-scripts#203]
After repairing a cask, you get a message advising that you can say e.g.
  `brew cask reinstall https://raw.githubusercontent.com/...`
to immediately installed the repaired cask. However, brew cask is deprecated, so I guess this should be
 `brew reinstall https://raw.githubusercontent.com/...`

There are also quite a few other instances of brew cask in the script, and I suppose those too need updating.

**Comment by vitorgalvao** [comment]
Fixed.
