### ISSUE TITLE
pkg-extract doesn't support pbzx payloads

### ISSUE THREAD

**Issue by core-code** [vitorgalvao/tiny-scripts#207]
this patch fixes it, depends on https://github.com/nrosenstein-stuff/pbzx being in `/usr/local/bin/`

`pbzx` is in MacPorts but seemingly not in Homebrew

```
-
-  /usr/bin/gzip --decompress --suffix '' --stdout "${payload}" | /usr/bin/cpio -i --preserve-modification-time 2> /dev/null
+  
+  first_four_bytes="$(head -c 4 "${payload}")"
+  if [[ $first_four_bytes == "pbzx"* ]]; then
+     /usr/local/bin/pbzx -n "${payload}" | /usr/bin/cpio -i --preserve-modification-time 2> /dev/null
+  else   
+    /usr/bin/gzip --decompress --suffix '' --stdout "${payload}" | /usr/bin/cpio -i --preserve-modification-time 2> /dev/null
+  fi

```

**Comment by core-code** [comment]
required for https://dl.teamviewer.com/download/version_15x/TeamViewerHost.dmg since version 15.30.3

**Comment by vitorgalvao** [comment]
Thank you. Done in https://github.com/vitorgalvao/tiny-scripts/commit/868b8de7d71c9de930899f91edaa90a64b964d5a and https://github.com/vitorgalvao/homebrew-tiny-scripts/commit/1faaf7551206035a7795346994797ab7dc54a8ef.
