### ISSUE TITLE
Please support 'subl -w' as editor. 

### ISSUE THREAD

**Issue by yurikoles** [vitorgalvao/tiny-scripts#23]
It's just as simple as it stands, with EDITOR set to `subl -w` cask-repair falls back to Xcode. With output:
```
/usr/local/bin/cask-repair: line 355: subl -w: command not found
```
For those curious: ` -w or --wait:        Wait for the files to be closed before returning`. As its stand in [Official Doc.](https://www.sublimetext.com/docs/3/osx_command_line.html) This switch is very useful for git and others, please don't force us to change it.

**Comment by vitorgalvao** [comment]
The command is supported. `atom -w` works, for example. That error simply means the command is not being found, not that `cask-repair` doesn’t support it. `cask-repair` simply reads your `EDITOR`, check that and your `PATH`.

**Comment by yurikoles** [comment]
I have tried to set EDITOR='atom -w' or EDITOR="atom -w" with no luck, atom and subl binaries are in same location: /usr/local/bin. Every time cask-repair reports same error :(.

**Comment by vitorgalvao** [comment]
What’s the output of `echo $PATH`?

**Comment by yurikoles** [comment]
```
/Users/yurikoles/.opam/system/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:/Users/yurikoles/.rvm/bin:/Users/yurikoles/bin:/Users/yurikoles/.rvm/gems/ruby-2.2.4/bin:/Users/yurikoles/.rvm/gems/ruby-2.2.4@global/bin:/Users/yurikoles/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/aria2/bin:/Users/yurikoles/.rvm/bin:/Users/yurikoles/.rvm/bin:/Users/yurikoles/go/bin:/ndk-bundle:/Users/yurikoles/.node_modules/bin:/Users/yurikoles/Library/Android/sdk/ndk-bundle:/usr/local/opt/jboss-as/libexec/bin:/Users/yurikoles/bin/depot-tools:/Users/yurikoles/.rvm/bin:/Users/yurikoles/.rvm/bin
```

**Comment by vitorgalvao** [comment]
What about `which atom` and `which subl`?

**Comment by yurikoles** [comment]
`/usr/local/bin/atom` 
`/usr/local/bin/subl`

**Comment by vitorgalvao** [comment]
Really have no idea what the issue is. I can’t reproduce, and never found other users with the issue (but I now it works for others, since I introduced it as a request).

[As you can see](https://github.com/vitorgalvao/tiny-scripts/blob/282caa0f98ba0cb92e76e6e00e644998fc55787e/cask-repair#L355), this is a single line, and the only thing I do it call `EDITOR`, nothing more.

**Comment by yurikoles** [comment]
May be it's because there is not return from ` "${EDITOR}" "${cask_file}"` it falls back to next expression?
Have you tried to set your EDITOR var to `subl -w` with Sublime Text 3?

**Comment by vitorgalvao** [comment]
> May be it's because there is not return from "${EDITOR}" "${cask_file}" it falls back to next expression?

No, your misinterpreting it.

`[[ -n "${EDITOR}" ]]` checks if `EDITOR` is set at all. If yes (`&&`), it uses it (`"${EDITOR}" "${cask_file}"`). If no (`||`) it opens with whatever is the default to ruby files on your system (`open -W "${cask_file}"`).

I haven’t used Sublime Text in a long time and the thing is the same with Atom (which I can run and you still can’t with the same error) so there’s no point.

**Comment by yurikoles** [comment]
One more question: do you use default bash from Apple or brew's one?

**Comment by vitorgalvao** [comment]
I use `zsh`. The script will call `/bin/bash`, but it will still read your shell’s `EDITOR`.

**Comment by vitorgalvao** [comment]
[This](https://github.com/vitorgalvao/tiny-scripts/pull/31) might fix your issue.
