### ISSUE TITLE
Is there any way to specify a notification on app launch?

### ISSUE THREAD

**Issue by mikemcduffie** [vitorgalvao/tiny-scripts#24]
Thanks for making this. Solves my issue of custom icon with `-open` URL option. 

Is there any way to specify the default notification displayed when the app is opened. Currently it has title "Terminal" with a blank message. 

It would be helpful to be able to notify users that the app is a part of another function/service, i.e. please don't delete or move.

**Comment by vitorgalvao** [comment]
Guessing you’re referring to [`customise-terminal-notifier`](https://github.com/vitorgalvao/tiny-scripts/blob/master/customise-terminal-notifier). It simply downloads and alters [`terminal-notifier`](https://github.com/julienXX/terminal-notifier), you [use it the same](https://github.com/julienXX/terminal-notifier#options).

**Comment by mikemcduffie** [comment]
Yes, sorry I wasn't clear but I'm referring to `customise-terminal-notifier`. 

I have no issues using the embedded binary via a command or script. The issue is the notification generated when a user double-clicks/opens the customized app. A blank notification titled "Terminal" appears. Is there anyway to edit a custom notification inside the customized app? Or alternately, could the app display a dialog box on open instead with relevant info? Basically I'm asking for an enhancement. 

On further thought I assume you're just bundling the standard terminal-notifier CLI binary in a standard app bundle, so this may all be a bridge too far. 

Either way, thanks again for making this app generator.
