### ISSUE TITLE
Make cask-repair work for contributors without push access to main repo

### ISSUE THREAD

**Issue by adityadalal924** [vitorgalvao/tiny-scripts#3]
Just tried out cask-repair (It's pretty helpful), but it looks like it doesn't want to work for me as I don't have push access to caskroom/homebrew-cask (as I'm not a maintainer).

Any way to modify it so that it pushes to `adityadalal924/homebrew-cask` instead?

Logs for more clarity:
```
 [.../homebrew-cask/Casks] > cask-repair amethyst.rb 
Already on 'master'
Your branch is up-to-date with 'origin/master'.
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Switched to a new branch 'update-amethyst'

{snip}

Type the new version (or leave blank to abort)
> 0.9.5
==> Fetching resources for Cask ./amethyst.rb
==> Downloading http://ianyh.com/amethyst/versions/Amethyst-0.9.5.zip
######################################################################## 100.0%
==> Success! Downloaded to -> /Library/Caches/Homebrew/amethyst-0.9.5.zip
audit for amethyst: passed

{snip}

Is everything correct? You can also make further manual edits (y/n/e) y[update-amethyst a5f902b] updated amethyst (0.9.5)
 1 file changed, 1 insertion(+), 1 deletion(-)
remote: Permission to caskroom/homebrew-cask.git denied to adityadalal924.
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': The requested URL returned error: 403
HEAD is now at a5f902b updated amethyst (0.9.5)
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Deleted branch update-amethyst (was a5f902b).

Submitted
```

Git Info, if it helps:
```
 [.../homebrew-cask/Casks] > git branch
* master
 [.../homebrew-cask/Casks] > git branch -r
  adityadalal924/master
  origin/HEAD -> origin/master
  origin/master
 [.../homebrew-cask/Casks] > git remote -v
adityadalal924	https://github.com/adityadalal924/homebrew-cask (fetch)
adityadalal924	https://github.com/adityadalal924/homebrew-cask (push)
origin	https://github.com/caskroom/homebrew-cask (fetch)
origin	https://github.com/caskroom/homebrew-cask (push)
````

Let me know if you need any more info (or if I just configured my git wrong). Thanks!

**Comment by vitorgalvao** [comment]
You don’t need push access to the official repo. When fixing a cask, the script works on a separate branch (created by it, and deleted when done). However, though it’s on my list, `cask-repair` doesn’t yet allow you to pick remotes (unlike `prfixmaster`, `prfixbranch`, and `fastmerge`, all in this repo).

Currently it assumes your personal remote is `origin` (will push to it), and the official remote is `upstream` (will pull from it). It seems like in your case the official remote is `origin`, hence why it is failing.

It works this way due to the way I update casks (my personal local repo to work on is not the same as the one the `brew cask` command uses). I’ll see if I can add the remote-picking option in the next dew days.

**Comment by vitorgalvao** [comment]
Just landed the feature (untested, but the changes were simple enough that it should be fine<sup>1</sup>). If you installed via homebrew, `brew update && brew upgrade cask-repair` will suffice.

Check `-h` or `--help` for more details, but `-l` and `--pull` are equivalent to pick a pull remote, and their counterparts are `-p` and `--push`. Both of them, if unset, default to their previous values (`upstream` and `origin`, respectively).

---
<sup>1</sup>Famous programming last words.

**Comment by adityadalal924** [comment]
Works well, just tried it out on https://github.com/caskroom/homebrew-cask/pull/14651

Automated the entire process quite nicely :+1: 

Thanks!
