### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by miccal** [vitorgalvao/tiny-scripts#40]
Hello vitorgalvao, first off thanks for the great `cask-repair` script. 

I have just performed a fresh install of macOS, and when I was setting up `cask-repair` for the first time as per the instructions in `CONTRIBUTING.md` on Homebrew Cask, I noticed something a little weird. 

The instructions say

```
# fork homebrew-cask to your account - only needed once
cd "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks"
hub fork
```

but when I went through the `hub fork` command and added my Github details, I noticed that when running `git remote -v` it listed

```
USER	git@github.com:USER/homebrew-cask.git (fetch)
USER	git@github.com:USER/homebrew-cask.git (push)
origin	https://github.com/caskroom/homebrew-cask (fetch)
origin	https://github.com/caskroom/homebrew-cask (push) 
```

instead of the usual

```
USER	https://github.com/USER/homebrew-cask (fetch)
USER	https://github.com/USER/homebrew-cask (push)
origin	https://github.com/caskroom/homebrew-cask (fetch)
origin	https://github.com/caskroom/homebrew-cask (push) 
```

and I could not push. I had to run `git remote set-url USER https://github.com/USER/homebrew-cask` to get things working.

I was just wondering if this is normal, or did I do something wrong in my initial setup?

**Comment by vitorgalvao** [comment]
You did everything well. Your debugging lead me to [this issue](https://github.com/github/hub/issues/1070) which is likely the culprit, as the behaviour changed.

Not sure why that is preventing the push, though. Since your solved your issue, I’ll close it and keep and eye out. If any one else bumps into this problem, I’ll know how to fix it and make the change in the documentation.

Thank you for the report and the debugging!

**Comment by miccal** [comment]
You're welcome.

**Comment by miccal** [comment]
Hello again, after [my strange `rubocop-cask` issue](https://github.com/vitorgalvao/tiny-scripts/issues/50) and my attempts to fix it making it worse, I reinstalled macOS and after setting up `cask-repair` for the first time as per the updated instructions in `CONTRIBUTING.md` with the `git config --local hub.protocol https` command, I again had an issue like the one above.

when running `git remote -v` this time it listed
```
USER    https://github.com/USER/homebrew-cask.git (fetch)
USER    https://github.com/USER/homebrew-cask.git (push)
origin  https://github.com/caskroom/homebrew-cask (fetch)
origin  https://github.com/caskroom/homebrew-cask (push) 
```
with an extra `.git`, and I again could not push. I had to again run `git remote set-url USER https://github.com/USER/homebrew-cask` to get things working.

**Comment by vitorgalvao** [comment]
`hub` is by far the biggest problem-maker in `cask-repair`. If I ever get hold a suitable alternative, I’ll switch in a heartbeat.

Just tried it myself, though, and though I do also get the extra `.git`, it did not prevent me from pushing.

**Comment by miccal** [comment]
Strange, for me it reported something along the lines `https://github.com/USER/homebrew-cask.git does not exist`. Could it be that `hub` somehow conflicts with `git`, as I have both installed via Homebrew?

**Comment by vitorgalvao** [comment]
> Could it be that `hub` somehow conflicts with `git`, as I have both installed via Homebrew?

I do to. `hub` is meant to extend `git`, so no conflict should occur. When you say `USER`, you mean `miccal` and not literally `USER`, correct?

**Comment by miccal** [comment]
Correct.

**Comment by miccal** [comment]
I may have found the issue - it seems that as long as `miccal` and `origin` are of the same format in `git remote -v`, it works. For example, having
```
miccal	https://github.com/miccal/homebrew-cask.git (fetch)
miccal	https://github.com/miccal/homebrew-cask.git (push)
origin	https://github.com/caskroom/homebrew-cask.git (fetch)
origin	https://github.com/caskroom/homebrew-cask.git (push)
```
is fine.

**Comment by vitorgalvao** [comment]
Weird. For testing, I’ve set it up so `origin` does not end in `git` and my personal one does, and still I see no error.

Will have to look further into it. Perhaps next week.

**Comment by miccal** [comment]
No problem - sorry I seem to be bothering you with weird problems!

**Comment by vitorgalvao** [comment]
Not at all! I appreciate it. `cask-repair` has grown so much it’s now a big blob of tacked on features. I have some cleaning up planned.

**Comment by miccal** [comment]
Found the issue - totally unrelated to `hub`, it was Little Snitch causing the problem.

Apologies for wasting your time!
