### ISSUE TITLE
Allow to edit the download path

### ISSUE THREAD

**Issue by muescha** [vitorgalvao/tiny-scripts#46]
in my case the app apple-event changed the download url form `.../AppleEvents_v0.6.zip` to `AppleEvents_v0.7_r.zip`. (see [Releases/appcast.xml](https://github.com/insidegui/AppleEvents/blob/master/Releases/appcast.xml) )

it would be nice if there is an additional question after the input for the version:

```
Type the new version (or leave blank to use the current one)
> 0.7
we use this url template:
https://github.com/insidegui/AppleEvents/releases/download/#{version}/AppleEvents_v#{version}.zip
download url with version "0.7":
https://github.com/insidegui/AppleEvents/releases/download/0.7/AppleEvents_v0.7.zip
Is the url template correct? You can also make further manual edits (y/n/e)
https://github.com/insidegui/AppleEvents/releases/download/#{version}/AppleEvents_v#{version}_r.zip
we use this url template:
https://github.com/insidegui/AppleEvents/releases/download/#{version}/AppleEvents_v#{version}_r.zip
download url with version "0.7":
https://github.com/insidegui/AppleEvents/releases/download/0.7/AppleEvents_v0.7_r.zip
Is the url template correct? You can also make further manual edits (y/n/e)
[...]
```

**Comment by vitorgalvao** [comment]
> it would be nice if there is an additional question after the input for the version

It’s right there:

> You can also make further manual edits (y/n/e)

Press `e`. Also, you have `--edit`/`-e` if you know beforehand you’ll want to make edits. Read the help (`--help`/`-h`).

**Comment by muescha** [comment]
`sha256` and `checkpoint` is new calculated if i press `e` and edit the cask afterwards?

**Comment by muescha** [comment]
ok - it changed - i canceled at this step because i was not thinking that it would recalculate the sha256 and the checkpoint - there should be a hint about this in the script
