### ISSUE TITLE
use the appcast xml

### ISSUE THREAD

**Issue by muescha** [vitorgalvao/tiny-scripts#47]
the repair script should use the appcast xml or allow to input a new appcast.xml

**Comment by vitorgalvao** [comment]
What do you mean?

If you want to change the `appcast`, simply use the `--edit` option or press `e` when the script asks you if everything is correct.

**Comment by muescha** [comment]
instead of manual type the version number etc. it could use the appcast to get the current version number

(in apple-events it is in https://github.com/insidegui/AppleEvents/releases.atom and also in https://github.com/insidegui/AppleEvents/tree/master/Releases/appcast.xml )

**Comment by vitorgalvao** [comment]
No, it cannot.

Appcasts are not standard, even amongst themselves (Sparkle, Github releases), so there’s no automated method that will work for all.
