### ISSUE TITLE
cask-repair: cannot submit

### ISSUE THREAD

**Issue by miccal** [vitorgalvao/tiny-scripts#50]
Hello vitorgalvao, I am experiencing a strange issue with `cask-repair` that I cannot resolve - when I get to the stage where the script asks
```
Is everything correct? You can also make further manual edits (y/n/e)
```
and I enter `y`, it then repeats the question after outputting the following line:
```
• ==> Installing or updating 'rubocop-cask' gem
```
Entering `y` a second time prints it twice:
```
• ==> Installing or updating 'rubocop-cask' gem
• ==> Installing or updating 'rubocop-cask' gem
```
then repeats the line
```
Is everything correct? You can also make further manual edits (y/n/e)
```

Any suggestions?

**Comment by vitorgalvao** [comment]
`cask-repair` auto-runs `brew cask style --fix` on your cask. That message was output by `brew cask style`, that uses the `rubocop-cask` gem make its checks.

Reason you’re probably getting that repeatedly is that it’s still installing it, so you have to wait a bit.

Try again now.

**Comment by miccal** [comment]
I thought that, but no matter how long I wait it just keeps going in a loop, and `gem update` reports `Nothing to update`.

**Comment by vitorgalvao** [comment]
What if you run `brew cask style --fix` on that cask, without `cask-repair`?

**Comment by miccal** [comment]
Hmmm...
```
ERROR:  Could not find a valid gem 'rubocop-cask' (~> 0.10.4), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)
Error: Failed to install/update the 'rubocop-cask' gem.
```

**Comment by vitorgalvao** [comment]
There’s your problem.

Try `gem uninstall rubocop-cask && gem install rubocop-cask`. If that doesn’t work, you may need to look at your ruby installation or it might be a temporary problem on rubygem’s side.

I tried it just now and it worked.

**Comment by miccal** [comment]
Bugger...
```
-bash-4.4.0- /Users/miccal [> gem install rubocop-cask
ERROR:  Could not find a valid gem 'rubocop-cask' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)
```

**Comment by vitorgalvao** [comment]
That looks like an SSL error. Question is if it’s on their side or yours. [Have you tried turning it off and on again](https://www.youtube.com/watch?v=kb2gzteVNa4)?

**Comment by miccal** [comment]
Yes I have rebooted my machine, I am not sure what has changed in the last 24 hours.

**Comment by miccal** [comment]
Okay, now I am really confused:

```
-bash-4.4.0- /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks [> gem uninstall rubocop-cask && gem install rubocop-cask
Successfully uninstalled rubocop-cask-0.10.4
Fetching: rubocop-cask-0.10.4.gem (100%)
Successfully installed rubocop-cask-0.10.4
Parsing documentation for rubocop-cask-0.10.4
Installing ri documentation for rubocop-cask-0.10.4
Done installing documentation for rubocop-cask after 0 seconds
1 gem installed
-bash-4.4.0- /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks [> brew cask style --fix aquaterm
==> Installing or updating 'rubocop-cask' gem
ERROR:  Could not find a valid gem 'rubocop-cask' (~> 0.10.4), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)
Error: Failed to install/update the 'rubocop-cask' gem.
```

**Comment by vitorgalvao** [comment]
That last one is definitely weird. Mind making that your bug report on [brew](https://github.com/Homebrew/brew), so ti can be properly diagnosed?
