### ISSUE TITLE
error: the requested upstream branch 'antonakv/cask-repair_update-deadbeef' does not exist

### ISSUE THREAD

**Issue by antonakv** [vitorgalvao/tiny-scripts#52]
Hi,

I have the same issue as in https://github.com/vitorgalvao/tiny-scripts/issues/26

$ cask-repair --help

This script requires 'hub' installed and configured.
If you have [Homebrew](http://brew.sh), you can install it with 'brew install hub'.
To configure it, run 'cd /usr/local/Homebrew && hub issue'. Your Github password will be required, but is never stored.
  
$ cd /usr/local/Homebrew && hub issue
github.com username: antonakv
github.com password for antonakv (never stored): 
   1594] Not all scripts installed to zsh/site-functions are completion scripts ( https://github.com/Homebrew/brew/issues/1594 )
   1593] Add --ask option to prompt for further action ( https://github.com/Homebrew/brew/pull/1593 )
   1592] formula: runtime deps of build deps aren't runtime ( https://github.com/Homebrew/brew/pull/1592 )
   1590] Fail if cask source already exists. ( https://github.com/Homebrew/brew/pull/1590 )
   1587] Incorrect selection of Xcode location ( https://github.com/Homebrew/brew/issues/1587 )
   1586] Cannot uninstall dependents unless the dependencies' formulae still exist ( https://github.com/Homebrew/brew/issues/1586 )
   1585] Crash in xquartz.rb: Error: undefined method `/' for nil:NilClass ( https://github.com/Homebrew/brew/issues/1585 )
   1566] Pruned 1 symbolic links from /usr/local - every day ( https://github.com/Homebrew/brew/issues/1566 )
   1556] Can't install on Sierra ( https://github.com/Homebrew/brew/issues/1556 )
   1555] revision bumped run-time dependencies are not protected ( https://github.com/Homebrew/brew/issues/1555 )
   1554] some build-time dependencies recorded as run-time dependencies ( https://github.com/Homebrew/brew/issues/1554 )
   1527] keg: update installed dependency resolution ( https://github.com/Homebrew/brew/pull/1527 )
   1526] Some tests are run multiple times ( https://github.com/Homebrew/brew/issues/1526 )
   1525] How should installed dependency resolution handle versions? ( https://github.com/Homebrew/brew/issues/1525 )
   1524] brew uninstall can have counter-intuitive (and frustrating) results ( https://github.com/Homebrew/brew/issues/1524 )
   1523] brew cask add upgrade/outdated/pin/unpin ( https://github.com/Homebrew/brew/pull/1523 )
   1471] Add --with-custom-python option to virtualenv formulæ ( https://github.com/Homebrew/brew/pull/1471 )
   1464] Use `launchctl` to get running processes by bundle ID. ( https://github.com/Homebrew/brew/pull/1464 )
   1432] metafiles: warn about missing metafiles  ( https://github.com/Homebrew/brew/pull/1432 )
   1408] Add :node special dependency ( https://github.com/Homebrew/brew/pull/1408 )
   1349] Merge Gemfiles. ( https://github.com/Homebrew/brew/pull/1349 )
   1343] Allow to install any spec ( https://github.com/Homebrew/brew/pull/1343 )
   1335] cask: activate GPG verification on install ( https://github.com/Homebrew/brew/pull/1335 )
   1314] [WIP] Refactor test suites. ( https://github.com/Homebrew/brew/pull/1314 )
   1297] Complain about HEP 6 violations. ( https://github.com/Homebrew/brew/pull/1297 )
   1292] Make stats from analytics available as a yearly report ( https://github.com/Homebrew/brew/issues/1292 )
   1247] minimum os requirement is not being inherited ( https://github.com/Homebrew/brew/issues/1247 )
   1237] migrate-formula-pr: new command ( https://github.com/Homebrew/brew/pull/1237 )
   1192] keg: create symlinks in opt for formula aliases ( https://github.com/Homebrew/brew/pull/1192 )
   1191] -L#{sysroot}/usr/lib isn't always removed by superenv with Xcode 8 ( https://github.com/Homebrew/brew/issues/1191 )
Homebrew anton$ cd "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks"
Casks anton$ 
Casks anton$ hub fork
Updating antonakv
remote: Counting objects: 74, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 74 (delta 55), reused 55 (delta 36), pack-reused 0
Unpacking objects: 100% (74/74), done.
From https://github.com/Caskroom/homebrew-cask
 * [new branch]      boom_uninstall -> antonakv/boom_uninstall
 * [new branch]      master         -> antonakv/master
new remote: antonakv
Casks anton$ outdated_cask='deadbeef'
Casks anton$ github_user='antonakv'
Casks anton$ cd "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks"
Casks anton$ cask-repair --pull origin --push $github_user $outdated_cask
-----------------------------------------------------------------------------------------------------------------------------------------------------------
cask 'deadbeef' do
  version '0.7.2'
  sha256 '8da871c4f8ab19515bb85119a85b32ed3917a8c01074afb8861a00debd3bb38e'

  url 'https://downloads.sourceforge.net/deadbeef/deadbeef-devel-osx-x86_64.zip'
  appcast 'https://sourceforge.net/projects/deadbeef/rss?path=/travis/osx/master',
          checkpoint: '34fb1506fb9797148a3191583ddd33c7279336876c6823a4c23e40431811e190'
  name 'DeaDBeeF'
  homepage 'http://deadbeef.sourceforge.net/'

  app 'deadbeef.app'
end
-----------------------------------------------------------------------------------------------------------------------------------------------------------
Type the new version (or leave blank to use the current one)
> 0.7.2
Paste the new URL (or leave blank to use the current one)
> 
==> Downloading external files for Cask ./deadbeef.rb
==> Downloading https://downloads.sourceforge.net/deadbeef/deadbeef-devel-osx-x86_64.zip
######################################################################## 100.0%
==> No checksum defined for Cask deadbeef, skipping verification
==> Success! Downloaded to -> /Users/anton/Library/Caches/Homebrew/Cask/deadbeef--0.7.2.zip
diff --git a/Casks/deadbeef.rb b/Casks/deadbeef.rb
index 6861b79..43d369f 100644
--- a/Casks/deadbeef.rb
+++ b/Casks/deadbeef.rb
@@ -1,10 +1,10 @@
 cask 'deadbeef' do
   version '0.7.2'
-  sha256 '8da871c4f8ab19515bb85119a85b32ed3917a8c01074afb8861a00debd3bb38e'
+  sha256 '7dc688cca32bf1ef2efbfb4f93c7464b1f935ad71e3d2e35fb06513a615bd7e8'
 
   url 'https://downloads.sourceforge.net/deadbeef/deadbeef-devel-osx-x86_64.zip'
   appcast 'https://sourceforge.net/projects/deadbeef/rss?path=/travis/osx/master',
-          checkpoint: '34fb1506fb9797148a3191583ddd33c7279336876c6823a4c23e40431811e190'
+          checkpoint: 'ed8178e68dd11ce0d03d31f8864e4eaa95cf45112764691f0b82793fcbd4dcb2'
   name 'DeaDBeeF'
   homepage 'http://deadbeef.sourceforge.net/'
 
-----------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? You can also make further manual edits (y/n/e) y
Submitting…
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: the requested upstream branch 'antonakv/cask-repair_update-deadbeef' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

There was an error submitting the pull request. Have you forked the repo and made sure the pull and push remotes exist?

How can I fix that ?
Please advice.

**Comment by vitorgalvao** [comment]
This report is a mess. Please use fenced code blocks.

Also, [like I said](https://github.com/vitorgalvao/tiny-scripts/issues/26#issuecomment-230815801), you can help me find a fix, but I’ll no longer look at that error. I cannot reproduce on clean VMs.

**Comment by antonakv** [comment]
So, you don't give sh*t about the issue.
Very professional approach ! Go ahead.

**Comment by vitorgalvao** [comment]
I do care about the issue. I have just exhausted all the options I know of and since I can’t reproduce, I cannot fix it. But I’ve already stated that.

Also, you’re not paying me for my time, and if you think insulting me will make me spend **my free time** to help you, you’re seriously wrong.

It’s always the ones with close to no contributions that make the bad reports, don’t read through the issues, and make demands of the free time of others.

I have no time to waste on abusers.
