### ISSUE TITLE
Support for usual brew formulae for cask-repair

### ISSUE THREAD

**Issue by mathbunnyru** [vitorgalvao/tiny-scripts#55]
Is it possible to use cask-repair to submit PRs to homebrew-core/Formula? If it's not, do you have plans to make it easier to submit PRs there?

Thank you for your awesome script.

**Comment by miccal** [comment]
@mathbunnyru `cask-repair` is specifically for Casks, but there is a [script for Formulas](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb).

**Comment by mathbunnyru** [comment]
@miccal Thanks!
