### ISSUE TITLE
Cask-repair won't work if Taps remote url are not in HTTP (ie. force ssh via gitconfig)

### ISSUE THREAD

**Issue by 0rax** [vitorgalvao/tiny-scripts#57]
Hi there,

I am currently running cask-repair on my machine for 6 month now and I noticed that I was not able to launch the script without commenting the following line in my gitconfig.

```
[url "git@github.com:"]
    insteadOf = https://github.com/
```

The error returned being:

```
`origin` is pointing to an incorrect remote (git@github.com:caskroom/homebrew-versions). It must start with https://github.com/caskroom/.
```

This causes a problem for me as I only push via ssh to Github and if this is not set I am not able to commit. Thus I need to comment those 2 lines before launching the script and un-comment them just after validating my modifications.

Would it be possible to accept both `git@github.com:caskroom/` as well as `https://github.com/caskroom/` as remote ?

This issue might arise for multiple people that forces this remote (this is one of the workaround to run `go get` on private repository for example).

Thanks a lot

**Comment by vitorgalvao** [comment]
Non-https remotes historically caused a lot of trouble, so I’m not very inclined to allow those. Yes, some people might be stopped from using the script, but not enough to be worth the hassle.

Edit `cask-repair` on your machine and comment out [line 396](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair#L396). That alone should fix it for your case. Please try it out and report back.

**Comment by 0rax** [comment]
It works fines once commented, thanks !

Would a command line option be something to consider then ? I don't really see myself having to do the modification each time the script is updated but aliasing cask-repair to `cask-repair -u` is pretty much fine.

I can understand that you do not wish to allow non-https remotes by default though I don't really see how they might cause problem.

**Comment by vitorgalvao** [comment]
> Would a command line option be something to consider then ?

Not really, that’d be a confusing option.

> I can understand that you do not wish to allow non-https remotes by default though I don't really see how they might cause problem.

This isn’t hypothetical. They did cause problems. That said, they did so before the script revamp, so I may have fixed those issues inadvertently. I’ll add `git@github.com:caskroom/` to that check in the script. If it causes problems in the future, I’ll deal with them then.

**Comment by 0rax** [comment]
Thanks a lot ! Your script is really useful and saves a lot of time when I want to push an upgrade to a casks !

**Comment by vitorgalvao** [comment]
[Done](https://github.com/vitorgalvao/tiny-scripts/commit/c61705f491564254fba96485768e57202ba20787).

**Comment by 0rax** [comment]
@vitorgalvao Just checked the code and tested. It is not working properly as ssh remote are `git@github.com:caskroom` and not `git@github.com/caskroom`.

**Comment by vitorgalvao** [comment]
Should be fixed now.

**Comment by 0rax** [comment]
That's working perfectly, thanks a lot !
