### ISSUE TITLE
failed pushing the pull request using cask-repair

### ISSUE THREAD

**Issue by OranShuster** [vitorgalvao/tiny-scripts#58]
after using "cask-repair nylas-mail" everything works right until the end  where i get the following message

`Aborted: 204 commits are not yet pushed to OranShuster/cask-repair_update-nylas-mail
(use `-f` to force submit a pull request anyway)
Aborted: 204 commits are not yet pushed to OranShuster/cask-repair_update-nylas-mail
(use `-f` to force submit a pull request anyway)

There was an error submitting the pull request. Please open a bug report on the repo for this script.`

My guess is that the revamped cask-repair might not like using already existing forks from the old cask-repair

**Comment by OranShuster** [comment]
Fixed it by going into the brew repo folder myself, deleting all the remotes from "git remote" and and deleted the branches

**Comment by vitorgalvao** [comment]
Closing as solved. Will keep an eye out for more people with this issue.

**Comment by neutric** [comment]
I have that issue every now and then. Since the commit is actually already pushed, I up until recently just went to github.com and did the PR manually. I believe that doing so occasionally leads to situations like [this](https://github.com/caskroom/homebrew-cask/pull/30275), where an old commit reappears in a PR. Something like this happened to me just a few days ago.

Similarly, sometimes I only get one of the two `Aborted: ...` messages, which then leads to the PR being opened by hub but with `Closes #.` without an issue number attached to the pull message. See e.g. [here](https://github.com/caskroom/homebrew-cask/pull/30098) and [here](https://github.com/caskroom/homebrew-cask/pull/30279).

Belonging to the latter:
```bash
% cask-repair -v 43.0.2442.991 opera
Updating taps… Already up-to-date.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
cask 'opera' do
  version '43.0.2442.806'
  sha256 'f8d709ef1bc2db3080aca7a786d8cc6c6cf6346e2e8bcca3caf42c6a4f6b3ee5'

  url "https://get.geo.opera.com/pub/opera/desktop/#{version}/mac/Opera_#{version}_Setup.dmg"
  name 'Opera'
  homepage 'https://www.opera.com/'

  app 'Opera.app'
end
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
==> Downloading external files for Cask ./opera.rb
==> Downloading https://get.geo.opera.com/pub/opera/desktop/43.0.2442.991/mac/Opera_43.0.2442.991_Setup.dmg
######################################################################## 100.0%
==> No checksum defined for Cask opera, skipping verification
==> Success! Downloaded to -> /Users/ah/Library/Caches/Homebrew/Cask/opera--43.0.2442.991.dmg
diff --git a/Casks/opera.rb b/Casks/opera.rb
index aa4671c64..f9c9fa98f 100644
--- a/Casks/opera.rb
+++ b/Casks/opera.rb
@@ -1,6 +1,6 @@
 cask 'opera' do
-  version '43.0.2442.806'
-  sha256 'f8d709ef1bc2db3080aca7a786d8cc6c6cf6346e2e8bcca3caf42c6a4f6b3ee5'
+  version '43.0.2442.991'
+  sha256 '8a13fa40182325d7f42fbb08777639461237594e7179c81199284a1169ff78f5'

   url "https://get.geo.opera.com/pub/opera/desktop/#{version}/mac/Opera_#{version}_Setup.dmg"
   name 'Opera'
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
Aborted: 703 commits are not yet pushed to neutric/cask-repair_update-opera
(use `-f` to force submit a pull request anyway)
```

**Comment by vitorgalvao** [comment]
@neutric Try `cask-repair --delete-branches`. Then do as @OranShuster: go to the repos and delete all remotes.

If the error happens again after that, please report back.

**Comment by neutric** [comment]
Will do so next time this problem pops up.
