### ISSUE TITLE
cask-repair enforces HTTPS for remote?

### ISSUE THREAD

**Issue by lunaryorn** [vitorgalvao/tiny-scripts#61]
I noticed that cask-repair explicitly creates the remote for the fork with HTTPS?  Why's that?

Is there any chance to get SSH support?  With 2FA enabled I find HTTPS is a nuisance to use.

**Comment by yurikoles** [comment]
@lunaryorn there is a trick described here: #57
just add to your .gitconfig the following:
```
[url "git@github.com:"]
    insteadOf = https://github.com/
```

**Comment by vitorgalvao** [comment]
It’s enforced with HTTPS because the alternative caused loads of issues. That was before the revamp, though, so those might’ve been fixed.

I have 2FA and never found it a nuisance, though.

**Comment by lunaryorn** [comment]
@vitorgalvao I presume that means you'll not add SSH nor accept any pull request that'd do so?

**Comment by vitorgalvao** [comment]
I’ll look at a PR, yes. Should be done around line `112`, in the `ensure_cask_repair_remote` function.

But It also means I’ll revert it at the first sign the problems are coming back.

**Comment by lunaryorn** [comment]
Thank you.  I understand your position and can relate to it, but I'd also not like to spent time on this change just to see it taken back out again at the first person with a flawed hub/SSH setup.  I am sorry.
