### ISSUE TITLE
Try some edge cases of the script

### ISSUE THREAD

**Issue by muescha** [vitorgalvao/tiny-scripts#63]
### Submit a second time

when i try to run the script a second time then i get this error:

```
Submitting…
Error creating pull request: Unprocessable Entity (HTTP 422)
A pull request already exists for muescha:cask-repair_update-dash.
Error creating pull request: Unprocessable Entity (HTTP 422)
A pull request already exists for muescha:cask-repair_update-dash.

There was an error submitting the pull request. Please open a bug report on the repo for this script.
```

i think in this case it should just show a note:

```
A pull request already exists for muescha:cask-repair_update-dash.
the commits are updated.
```

### Submit a second time but with other Version number 4.0.2

for example when the Version changes again and the pull request is not accepted

```
diff --git a/Casks/dash.rb b/Casks/dash.rb
index f9dff0b..ccf7f16 100644
--- a/Casks/dash.rb
+++ b/Casks/dash.rb
@@ -1,10 +1,10 @@
 cask 'dash' do
-  version '4.0.0'
-  sha256 'dadd3c5ba718053cf7797cb31cc2aa26779e0ffe09a2fd1e8ca19f80f63c9ab2'
+  version '4.0.2'
+  sha256 '2ef4d0721a89feb680bb416fd7694cbec5441df442b64aabb8b7abbaa5c9b3f3'
 
   url "https://kapeli.com/downloads/v#{version.major}/Dash.zip"
   appcast "https://kapeli.com/Dash#{version.major}.xml",
-          checkpoint: '8099212241b4aa0752094cc40df311037be1dab2c87389f988022fceb53661f4'
+          checkpoint: 'ed127f51a54c198287e90ea386f6b746c3dc2b78bc8d061c5b52d6e9919588e4'
   name 'Dash'
   homepage 'https://kapeli.com/dash'
 
--------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
Aborted: 1 commits are not yet pushed to muescha/cask-repair_update-dash
(use `-f` to force submit a pull request anyway)
Aborted: 1 commits are not yet pushed to muescha/cask-repair_update-dash
(use `-f` to force submit a pull request anyway)

There was an error submitting the pull request. Please open a bug report on the repo for this script.

```

in this case it becomes a little messy:

<img width="1419" alt="bildschirmfoto 2017-02-21 um 20 36 54" src="https://cloud.githubusercontent.com/assets/184316/23181993/4d46b5f4-f877-11e6-8e65-90e090b13137.png">

#### there is an error this error:

`1 commits are not yet pushed to muescha/cask-repair_update-dash`

but  the commit is submitted to the pull request

then script it should say:

```
A pull request already exists for muescha:cask-repair_update-dash.
the commits are updated.
```

#### Pull Request Name is not updated

the pull request name don't show the new version 4.0.2 (it is still at 4.0.1), but the commit is at 4.0.2

**Comment by vitorgalvao** [comment]
> Error creating pull request: Unprocessable Entity (HTTP 422)

That specific issue is `hub`-related (search for the error on Google) and generally happens with certain git configs. You can see from the other issues (e.g. #20) how much time I’ve already wasted on it.

Unfortunately, I won’t keep shooting in the dark. I’m happy to take a PR that squashes the problem for good, but don’t intend to waste much longer trying to diagnose it. It only affects a small set of users.

> Aborted: 1 commits are not yet pushed to muescha/cask-repair_update-dash

See https://github.com/vitorgalvao/tiny-scripts/issues/58.

> Pull Request Name is not updated

Fixing that is way more work than it’s worth. It isn’t a big deal and only happens occasionally.

**Comment by muescha** [comment]
ok :) happy coding

**Comment by muescha** [comment]
maybe related: https://github.com/github/hub/issues/867

if we could check before an `hub pull-request` if there an pull request already exists, then a better error message could be displayed
