### ISSUE TITLE
cask-repair "failed to change to directory of [cask]"

### ISSUE THREAD

**Issue by giannitm** [vitorgalvao/tiny-scripts#70]
<img width="256" alt="screen shot 2017-04-17 at 23 16 19" src="https://cloud.githubusercontent.com/assets/25732197/25106922/2d418324-23c4-11e7-86b3-4a954fd15564.png">

<img width="567" alt="screen shot 2017-04-17 at 23 15 57" src="https://cloud.githubusercontent.com/assets/25732197/25106921/29d2c0c2-23c4-11e7-9e5e-cc5e707e5b9e.png">

I am unable to reproduce this issue with other casks (at least, I haven't found one that reproduces this issue), however it happens every time I attempt to use the `cask-repair` script to update this cask, `chirp-daily`. I've tried running `cask-repair -e chirp-daily` but the same error is produced.

**Comment by vitorgalvao** [comment]
Fixed. There was a duplicate in the repos (see how it appears in both `homebrew-cask` and `homebrew-versions`, in the messages).
