### ISSUE TITLE
cask-repair not automatically calculating appcast checkpoints

### ISSUE THREAD

**Issue by giannitm** [vitorgalvao/tiny-scripts#72]
To save time, when adding a new `appcast`, I leave the `checkpoint` field blank, with only a pair of single quotes.

`checkpoint: ''`

Usually, `cask-repair` will automatically calculate the checkpoint hash, but occasionally it will not. I am not entirely sure why, and it seems to be random chance (but I know this is unlikely to happen, as scripts do not have a mind of their own). I may be making unfounded correlations, but the issue seems to happen whenever I am editing a cask with `version :latest` and/or `sha256 :no_check`.

I don't know if there is a link, but that is all I can think of. Let me know if further information is required to resolve the issue.

**Comment by vitorgalvao** [comment]
> To save time, when adding a new `appcast`, I leave the `checkpoint` field blank, with only a pair of single quotes.
>
> `checkpoint: ''`

I do the same.

> but the issue seems to happen whenever I am editing a cask with `version :latest` and/or `sha256 :no_check`.

But does it happen if it’s `version :latest` and you change `version` to something else? Casks with `appcast`s should never be `:latest` anyway

**Comment by giannitm** [comment]
I will have to check that. I'll try changing the version to `:latest` on one of the casks, and see what happens.

**Comment by giannitm** [comment]
@vitorgalvao This is the result:

<img width="899" alt="screen shot 2017-04-30 at 14 08 41" src="https://cloud.githubusercontent.com/assets/25732197/25564597/9c7e3266-2dae-11e7-819a-a5a9305db1af.png">

<img width="919" alt="screen shot 2017-04-30 at 14 10 09" src="https://cloud.githubusercontent.com/assets/25732197/25564600/c3660ba6-2dae-11e7-9bdd-993b07ce2924.png">

**Comment by vitorgalvao** [comment]
Fixed.
