### ISSUE TITLE
cask-repair seems to fail for 2-factor authentication

### ISSUE THREAD

**Issue by spott** [vitorgalvao/tiny-scripts#83]
I did `cd $(brew --repository) && hub issue`, and was able to log in with 2-factor fine, but a `cask-repair gog-galaxy` did not ask for my 2-factor code (it only asked for my username and password).

The issue received was: 

```
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

If there is anything else needed, let me know.

**Comment by yurikoles** [comment]
It's an issue in `hub` and should be fixed [upstream](/github/hub/issues).

**Comment by spott** [comment]
It appears to be [this](https://github.com/github/hub/issues/1488) issue.

**Comment by spott** [comment]
Someone else chimed in on the issue and mentioned that changing the protocol to `git` solved it.

As a workaround, would this be doable in cask-repair?

**Comment by vitorgalvao** [comment]
None of those things are the issue. Plenty of users have those settings with no adverse effects.

**Comment by spott** [comment]
I just changed my origins to using `git@` and that solved the problem as a workaround.  So while this is definitely an issue with `hub`, I think it isn't entirely accurate to say "None of those things are the issue."

**Comment by spott** [comment]
Weird... It worked for one repository, but not another.

So, never mind.

**Comment by hovancik** [comment]
I'm getting 
```
Submitting…
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```
and I do not have 2FA

**Comment by yurikoles** [comment]
@hovancik please try receipt in issue-template. Just try to create new issue on this repo.

**Comment by hovancik** [comment]
github ssh worked fine, I also added the config file. still the same.
