### ISSUE TITLE
Create Pull Request Fails

### ISSUE THREAD

**Issue by jasmas** [vitorgalvao/tiny-scripts#84]
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
Username for 'https://github.com': jasmas
Password for 'https://jasmas@github.com':
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

There was an error submitting the pull request. Please open a bug report on the repo for this script (https://github.com/vitorgalvao/tiny-scripts).

**Comment by jasmas** [comment]
Is it possible this script does not support two factor authentication?

**Comment by yurikoles** [comment]
@jasmas why don't you use search?

@vitorgalvao please consider adding special case for this error of `hub` that will give link to upstream issue

**Comment by vitorgalvao** [comment]
@yurikoles Catching all the errors and deciding what to do with them is a lot of ugly work, in bash.

But I agree this repeated issue is indeed a problem, so I’ve approached it with [an issue template.](https://github.com/vitorgalvao/tiny-scripts/issues/new)
