### ISSUE TITLE
cask-repair should not ignore hub global configuration for remotes

### ISSUE THREAD

**Issue by jasmas** [vitorgalvao/tiny-scripts#85]
cask-repair does not work for me and I otherwise have zero issues with hub or pushing from git to github. I do it frequently and never have issues. However, running cask-repair results in the error which shall not be named. 

The reason cask-repair is not working in my case, absent of any other issues with hub at all, is because you are specifying an https remote regardless of hub configuration on the system. By default hub does not create an https remote, but uses git by default. From the manual:

```
    git fork
        $ git fork
        [ repo forked on GitHub ]
        > git remote add -f YOUR_USER git@github.com:YOUR_USER/CURRENT_REPO.git
```

Adding https remotes is opt-in for hub. Also from the manual:

```
    HTTPS instead of git protocol
        If  you  prefer  the  HTTPS protocol for GitHub repositories, you can set "hub.protocol" to "https". This will affect clone, fork, remote add and other operations that expand
        references to GitHub repositories as full URLs that otherwise use git and ssh protocols.
 
        "hub.protocol" only applies when the "OWNER/REPO" shorthand is used instead of a full git URL.
 
            # default behavior
            $ git clone defunkt/repl
            < git clone >
 
            # opt into HTTPS:
            $ git config --global hub.protocol https
            $ git clone defunkt/repl
            < https clone >
```

Since you are adding the remote manually, cask-repair prompts for credentials where git and hub otherwise do not on my system. 

Using https is not acceptable for me because I use two-factor authentication. Although hub has been updated to support two-factor authentication, it is not supported for pushing to a remote repository over https. In order to do so I would have to create a personal access token.

I'm not sure if there is a specific reason you chose to create an https remote. If not, switching to a git remote would be an easy work-around. The script should probably check hub.protocol in the global git configuration and use the protocol specified there, however, if the key is absent it should default to the git protocol to mimic the behavior of hub.

Another option would be to just let hub create the remote. If the remote should point to the fork hub created anyway, I don't see why this isn't the best option. For now it would need to use the default remote name which is the github username, but there is an open issue for hub to support a custom name in the future. https://github.com/github/hub/issues/762

**Comment by vitorgalvao** [comment]
Addressed in #86. If you’re making a PR to tackle an issue, please do not open the issue. Make your point in the PR, so we have a contained conversation. Otherwise the repo gets cluttered and the conversation fragmented.

I’ll accept a PR that fixes this as long as nothing else breaks.
