### ISSUE TITLE
cask-repair fails when prompting for password

### ISSUE THREAD

**Issue by jbeda** [vitorgalvao/tiny-scripts#9]
When using an `https` based remote, something is getting in the way of capturing the username/password for github.

```shell
$ cask-repair --pull origin --push jbeda consul
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
cask 'consul' do
  version '0.6.1'
  sha256 '358654900772b3477497f4a5b5a841f2763dc3062bf29212606a97f5a7a675f3'

  # hashicorp.com is the official download host per the vendor homepage
  url "https://releases.hashicorp.com/consul/#{version}/consul_#{version}_darwin_amd64.zip"
  name 'Consul'
  homepage 'https://www.consul.io/'
  license :mpl

  binary 'consul'
end
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Type the new version (or leave blank to abort)
> 0.6.0
==> Downloading external files for Cask ./consul.rb
==> Downloading https://releases.hashicorp.com/consul/0.6.0/consul_0.6.0_darwin_amd64.zip
######################################################################## 100.0%
==> No checksum defined for Cask consul, skipping verification
==> Success! Downloaded to -> /Library/Caches/Homebrew/consul-0.6.0.zip
audit for consul: passed
diff --git a/Casks/consul.rb b/Casks/consul.rb
index c67b778..a4dc885 100644
--- a/Casks/consul.rb
+++ b/Casks/consul.rb
@@ -1,6 +1,6 @@
 cask 'consul' do
-  version '0.6.1'
-  sha256 '358654900772b3477497f4a5b5a841f2763dc3062bf29212606a97f5a7a675f3'
+  version '0.6.0'
+  sha256 '29ddff01368458048731afa586cec5426c8033a914b43fc83d6442e0a522c114'

   # hashicorp.com is the official download host per the vendor homepage
   url "https://releases.hashicorp.com/consul/#{version}/consul_#{version}_darwin_amd64.zip"
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? You can also make further manual edits (y/n/e) y
Username for 'https://github.com': Password for 'https://github.com':
remote: Anonymous access to jbeda/homebrew-cask.git denied.
fatal: Authentication failed for 'https://github.com/jbeda/homebrew-cask.git/'
Error creating pull request: Unprocessable Entity (HTTP 422)
Missing field: "head_sha"
Missing field: "base_sha"
No commits between master and update-consul

Submitted
```

I'm not sure what is going on here but I suspect that it is the ``--quiet`` flag to the `git push`.

Also, this bash script continues to blunder on when errors are encountered.  I'd suggest you set the following options (for pretty much any substantial bash script) to reduce unexpected behavior:

```
set -o errexit
set -o nounset
set -o pipefail
```

If there is still clean up to be done even in these error cases, consider using a `trap` on `ERR` or `EXIT`.

**Comment by vitorgalvao** [comment]
Removed output of `doctor` commands, since it isn’t really useful. I would, however, like to know the installed versions of `cask-repair` and `hub`.

As for the `set` options, I usually don’t set them deliberately (for various reasons), but I should in this case.

To be honest, ideally I wouldn’t even let the script start unless `hub` was already configured (similarly to [what I do for `ghi`](https://github.com/vitorgalvao/tiny-scripts/blob/2ff81dbf5b5c81d05b6a207f09c002607a0fa8d1/prfixmaster#L8L15) in other scripts. Unfortunately, [they don’t provide a way to do that](https://github.com/github/hub/issues/225), but if this can cause an issue with `cask-repair`, I’d rather just go with the original idea and not let it run until configured.

I don’t really understand what happened in your case, though, could you clarify? For one, the requests for github username and password are a bit strange (they differ from what I just got in my quick test), but what happened there exactly? Did you simply <kbd>↩</kbd> through them?

**Comment by vitorgalvao** [comment]
Figured out an acceptable way to suggest how to configure `hub` prior to running the script, which I prefer and should fix your issue (since you won’t get there).

But I’d still like to know details of

> I don’t really understand what happened in your case, though, could you clarify? For one, the requests for github username and password are a bit strange (they differ from what I just got in my quick test), but what happened there exactly? Did you simply <kbd>↩</kbd> through them?

**Comment by vitorgalvao** [comment]
Closing for lack of reply.

**Comment by jbeda** [comment]
@vitorgalvao Sorry I dropped the ball here.  This stuff got filtered in my mail.

With the line:

```
Username for 'https://github.com': Password for 'https://github.com':
```

I didn't just hit return.  It (`git`? `hub`?) output that one line and was waiting for input.  Regardless if I put in my username or github password, things would proceed the same.  Note that if I use ssh based remotes (with my `ssh-agent` running) things work fine.
