### ISSUE TITLE
Solved: Error creating pull request: Unprocessable Entity (HTTP 422)

### ISSUE THREAD

**Issue by giovino** [vitorgalvao/tiny-scripts#90]
I experienced the error message `Error creating pull request: Unprocessable Entity (HTTP 422)` when using cask-repair for the very first time. 

It turns out that the settings in my ssh config were not passing my github ssh key appropriately. I was steered towards this as a potential cause due to this comment: [specify your public key](https://github.com/vitorgalvao/tiny-scripts/issues/20#issuecomment-316447787)

I was on a new machine and had yet to test github connectivity with ssh. I used this command to verify github ssh was broken:

```
$ ssh -T git@github.com -v
```
Reference: https://help.github.com/articles/testing-your-ssh-connection/

The resolution I put in place was adding the following to my .ssh/config file:

```
Host github.com
Hostname github.com
User git
IdentityFile /path/to/ssh/key
```

Once I fixed the authentication issues to Github using SSH, the error message `Error creating pull request: Unprocessable Entity (HTTP 422)` no longer appeared. 

It makes sense `cask-repair` would fail once I understood the root cause of the issue. I don't know if this is something `cask-repair` could or should try to assist with; regardless maybe this report will help the next person that finds themselves in a similar state.

**Comment by vitorgalvao** [comment]
Thank you. [Incorporated your instructions into the issue template](https://github.com/vitorgalvao/tiny-scripts/commit/11e2e731724168a2d78536eb6b084e058017def9).

**Comment by gtmgianni** [comment]
I kept getting the same 422 error, but fixed it by using Git over HTTPS instead of SSH – I changed the URL for the remote created by `cask-repair` from `git@github.com:gtmgianni/homebrew-cask.git` to `https://github.com/gtmgianni/homebrew-cask.git`.

Should that be added to the issue template?

**Comment by lantrix** [comment]
For me hub had set it up github access as https and I was still getting `Unprocessable Entity (HTTP 422)`.

```sh
$ cat ~/.config/hub
github.com:
- user: lantrix
  oauth_token: 1111111111111111aaaaaaaaa
  protocol: https
```

I did the same as @giovino to fix the error, and changed it to an SSH connection instead.
Config for `homebrew-cask` git repo and `github.com` SSH connections shown below.

```sh
$ cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
$ cat .git/config |grep lantrix
[remote "lantrix"]
	url = git@github.com:lantrix/homebrew-cask.git
	fetch = +refs/heads/*:refs/remotes/lantrix/*
$cat ~/.ssh/config
Host github.com
Hostname github.com
User git
IdentityFile /Users/ted/.ssh/id_rsa

```

Hope this helps someone else.
