### ISSUE TITLE
Add stuff to docs to prevent "Unprocessable Entity (HTTP 422)"

### ISSUE THREAD

**Issue by fepegar** [vitorgalvao/tiny-scripts#91]
Hi,

I did come here because I was getting the error of the issue template. After getting it I googled for some time, checked the docs at `homebrew-cask`, the ones here, some issues on GitHub, etc. I finally figured it out when I read #89 and @vitorgalvao said he should have read the issue template. So I clicked on "**New issue**" and followed the instructions. Btw, I only had to do [this](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) for it to work.

My point is: wouldn't it be easier for users to have this info in the [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) document of `homebrew-cask`? That would have saved *me* some time.

**Comment by vitorgalvao** [comment]
> After getting it I googled for some time, checked the docs at `homebrew-cask`, the ones here, some issues on GitHub, etc.

What you should’ve done was come here straight away and open an issue *like the error message tells you to*.

That message is always improving. Thank you for your feedback and I’ll keep it in mind, but for now it stays as it is.

**Comment by muescha** [comment]
i like to reopen this issue

it would also have this in documentation, because browsing through all the `Unprocessable Entity` issues to find a solution is not that nice. also i would like to have a solution without to setup an ssh key for the connection.

the result is: it is not working for me and i don't have more time to dig in this issue. and i can not update outdated formulas :(

**Comment by vitorgalvao** [comment]
> i like to reopen this issue

No. There’s no point in leaving open an issue without a clear goal.

> it would also have this in documentation, because browsing through all the `Unprocessable Entity` issues to find a solution is not that nice.

There is no achieved solution. If there were, this would not still be an issue. Go to the source. This is an `hub` issue, not a `cask-repair` one, and there are issues there to track this.

> i would like to have a solution without to setup an ssh key for the connection.

You don’t have to do it. That’s the solution for people that use a ssh key, as this issue typically affects them.

> the result is: it is not working for me and i don't have more time to dig in this issue.

Neither do I! And I’ve wasted more time on this than everyone else. Are my time and sanity not valuable?

> and i can not update outdated formulas :(

You can do it manually, just as it was before this script existed and a ton of people still do.

**Comment by muescha** [comment]
you completely right
sorry for wasting your time

PS: thx for pointing to it as an only 'hub' issue
