### ISSUE TITLE
[FR]Interactive mode of commit and PR for cask-repair

### ISSUE THREAD

**Issue by yurikoles** [vitorgalvao/tiny-scripts#94]
Please add option to edit a commit message (git) and a PR text (hub) to add some manual comments. Because now the only option is to edit it on the site after sending PR, which frustrates sender and reviewers, especially one wants to edit title of message.

**Comment by vitorgalvao** [comment]
Not going to happen.

`cask-repair` is a tool for quick updates, not a full-fledged github client. Editing the message on the site after submission is more than adequate, and I see no frustrated reviewers.

If you’re changing the message so often that it frustraste you, then you’re not using `cask-repair` for what it’s intended.
