### ISSUE TITLE
Aborted: 31 commits are not yet pushed

### ISSUE THREAD

**Issue by fepegar** [vitorgalvao/tiny-scripts#95]
My command:
```
➜  ~ cask-repair --cask-version 4.7.0.26221,675049 slicer-nightly -i
```

The error:
```
Submitting…
Aborted: 31 commits are not yet pushed to fepegar/cask_repair_update-slicer-nightly
(use `-f` to force submit a pull request anyway)
Aborted: 31 commits are not yet pushed to fepegar/cask_repair_update-slicer-nightly
(use `-f` to force submit a pull request anyway)

There was an error submitting the pull request. Please open a bug report on the repo for this script (https://github.com/vitorgalvao/tiny-scripts).
```

I also tried this:
```
➜  ~ cask-repair --delete-branches
remote: Repository not found.
fatal: repository 'https://github.com/fepegar/homebrew-cask/' not found
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by vitorgalvao** [comment]
Delete the repo and try again.

Also, the cask token *must* be the last argument.

**Comment by fepegar** [comment]
I already tried to delete it, but I don't have that fork. Should I delete it from my machine? Where can I find it?

I tried putting the cask token at the end, got the same.

Why do you close the issue? Should I open a new one if I still have questions?

**Comment by fepegar** [comment]
> No, we can just continue talking. I close issues fast because many people never reply and the issue stays lingering. This way if I think I have the fix I give it and close the issue. That does not mean the conversation is over. If I deem necessary, I’ll reopen.
Ok, thanks for the explanation.

> Try `brew untap caskroom/versions`.
That worked, thank you. I'll let you know if this happens again.
