### ISSUE TITLE
cask-repair cleared out my current working directory

### ISSUE THREAD

**Issue by johnjelinek** [vitorgalvao/tiny-scripts#96]
```
$ cask-repair ovftool
Updating taps… ^Cerror: Cannot delete branch 'master' checked out at
'/Users/johnjelinek/code/myapp' #<--- WAAAAAAT THAT'S NOT THE BREW DIR
```
😭 why did it checkout master of my current working directory, I lost all my work.

**Comment by vitorgalvao** [comment]
`ovftool` does not exist in any official repo. `cask-repair` wouldn’t work and warn you.

```bash
$ cask-repair ovftool
Updating taps… Already up-to-date.
No such cask was found in any official repo (ovftool).
```

The reason it checkedout master was [as part of the cleanup process](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair#L298L308), since you aborted. The result was unfortunate and due to a few coincidences. I hope you haven’t lost much.

[This has now been fixed](https://github.com/vitorgalvao/tiny-scripts/blob/07b9baa50334b8d90efd7b949d0007a518bfe8e1/cask-repair#L301).

**Comment by johnjelinek** [comment]
Thanks for the fix. Only lost a week of work. :cry:

**Comment by vitorgalvao** [comment]
> Only lost a week of work.

Holy crap. Why so long without any commit?

**Comment by johnjelinek** [comment]
Because it was only about 100 LOC and was iterating on a few different
ideas before commit.

**Comment by johnjelinek** [comment]
Ahh! It happened again! I guess I didn't realize that an upgrade didn't happen. I committed stuff this time, but I was working in a different branch, when I `^C`'d, it deleted my branch and put me back in `master`. WHAT! -- this one was multiple weeks of work gone.

**Comment by johnjelinek** [comment]
I've updated for sure now, but this is super unfortunate.

**Comment by tsparber** [comment]
Maybe you are lucky and the commits are still in the [git reflog](https://git-scm.com/docs/git-reflog).
This log contains all local commit objects until the repo is garbage collected. Using this it should be possible to [restore a deleted branch](https://confluence.atlassian.com/bbkb/how-to-restore-a-deleted-branch-765757540.html).

**Comment by vitorgalvao** [comment]
> Maybe you are lucky and the commits are still in the git reflog.

Issue is all changes were uncommitted.

**Comment by tsparber** [comment]
> I committed stuff this time, but I was working in a different branch, when I ^C'd, it deleted my branch and put me back in master. WHAT! -- this one was multiple weeks of work gone.

I was referring to this https://github.com/vitorgalvao/tiny-scripts/issues/96#issuecomment-322546645. 😉
